import type { Market, Notification, Post, User, WalletSettings, PrivacySettings } from '../types';

const sportsRules = `This market resolves using the official result after the first 90 minutes of regular play plus stoppage time. If the game is postponed, the market remains open until the game is completed. If the game is cancelled without a replacement, it resolves according to the published market policy.\n\nThe primary resolution source is the official statistics published by the governing body or event organizer. If official statistics are unavailable, a consensus of credible reporting may be used.`;
const standardRules = `This market resolves to “Yes” if the listed price is reached through 11:59 PM ET on the final day of the year specified in the title. Price action before this market's creation is not considered.\n\nThe primary resolution source is the official announcement or named market data source. If no official result is available, a consensus of credible reporting may be used.`;

export const markets: Market[] = [
  { id:'dem-2028', title:'Democratic Presidential Nominee 2028', category:'Recommend', subcategory:'Hot', volume:'$1.27B', more:49, outcomes:[{label:'Alexandria Ocasio-Cortez',odds:'4.78x',probability:21},{label:'Jon Ossoff',odds:'6.75x',probability:15}], rules:standardRules },
  { id:'president-2028', title:'Presidential Election Winner 2028', category:'Recommend', subcategory:'Hot', volume:'$693.1M', more:50, outcomes:[{label:'JD Vance',odds:'4.28x',probability:23},{label:'Alexandria Ocasio-Cortez',odds:'7.06x',probability:14}], rules:standardRules },
  { id:'rep-2028', title:'Republican Presidential Nominee 2028', category:'Recommend', subcategory:'Hot', volume:'$691.7M', more:40, outcomes:[{label:'J.D. Vance',odds:'2.11x',probability:47},{label:'Marco Rubio',odds:'5.15x',probability:19}], rules:standardRules },
  { id:'henan', title:'Wuhan San Zhen FC vs. Henan FC', category:'Sports', subcategory:'Soccer', volume:'$1.74K', more:1, outcomes:[{label:'Henan FC',odds:'1.14x',probability:87,color:'#1677ff'},{label:'Draw',odds:'1.28x',probability:78,color:'#ff7b3b'},{label:'Wuhan San Zhen FC',odds:'10.00x',probability:10,color:'#43c6d5'}], rules:sportsRules },
  { id:'birmingham', title:'Birmingham Legion FC vs. New Mexico United', category:'Sports', subcategory:'Soccer', volume:'$6.13K', more:1, outcomes:[{label:'New Mexico United',odds:'33.33x',probability:3},{label:'Draw',odds:'100.00x',probability:1}], rules:sportsRules },
  { id:'bitcoin-2026', title:'What price will Bitcoin hit in 2026?', category:'Crypto', subcategory:'Target Price', volume:'$60.54M', more:43, outcomes:[{label:'↓ 75,000',odds:'1.14x',probability:87,tradeAction:'Sell',color:'#1677ff'},{label:'↓ 70,000',odds:'1.51x',probability:66,tradeAction:'Sell',color:'#ff7b3b'},{label:'↑ 85,000',odds:'1.61x',probability:62,tradeAction:'Buy',color:'#43c6d5'},{label:'↑ 90,000',odds:'2.33x',probability:43,tradeAction:'Buy',color:'#9e91ee'}], rules:standardRules },
  { id:'bitcoin-august', title:'What price will Bitcoin hit in August?', category:'Crypto', subcategory:'Target Price', volume:'$21.99M', more:21, outcomes:[{label:'↓ 77,500',odds:'1.25x',probability:80,tradeAction:'Sell'},{label:'↑ 80,000',odds:'1.53x',probability:65,tradeAction:'Buy'}], rules:standardRules },
  { id:'ethereum-2026', title:'What price will Ethereum hit in 2026?', category:'Crypto', subcategory:'Target Price', volume:'$12.69M', more:21, outcomes:[{label:'↓ 2,250',odds:'1.29x',probability:78,tradeAction:'Sell'},{label:'↑ 2,750',odds:'1.49x',probability:67,tradeAction:'Buy'}], rules:standardRules },
];

export const users: User[] = [
  {id:'current',displayName:'Peter Kingsley',username:'peterk',initials:'PK',bio:'Prediction markets, crypto and transparent public thinking.',specialization:['Markets','AI','Crypto'],followers:284,following:96,accuracy:64,performance:4.8,consistency:71,contrarian:58,isFollowing:false,isCurrent:true,portfolioPublic:true},
  {id:'sarah',displayName:'Sarah Kim',username:'sarahk',initials:'SK',bio:'Crypto + macro. Publishing the thesis before the outcome.',specialization:['Crypto','Macro'],followers:12840,following:243,accuracy:78,performance:18.4,consistency:86,contrarian:74,isFollowing:true,portfolioPublic:true},
  {id:'marcus',displayName:'Marcus Reed',username:'marcusreads',initials:'MR',bio:'Risk-first crypto trader. Wins and losses stay public.',specialization:['Crypto'],followers:4210,following:310,accuracy:66,performance:-3.7,consistency:73,contrarian:61,isFollowing:true,portfolioPublic:true},
  {id:'amina',displayName:'Amina Bello',username:'aminab',initials:'AB',bio:'Football markets and lineup-driven probabilities.',specialization:['Sports'],followers:7860,following:188,accuracy:74,performance:9.2,consistency:82,contrarian:52,isFollowing:true,portfolioPublic:false},
  {id:'michael',displayName:'Michael Chen',username:'mchen',initials:'MC',bio:'Macro regimes, elections, and long-duration markets.',specialization:['Macro','Markets'],followers:9620,following:402,accuracy:72,performance:6.1,consistency:80,contrarian:79,isFollowing:false,portfolioPublic:true},
  {id:'elena',displayName:'Elena Rossi',username:'elenar',initials:'ER',bio:'On-chain research and liquidity conditions.',specialization:['Crypto','AI'],followers:15430,following:221,accuracy:76,performance:13.7,consistency:88,contrarian:71,isFollowing:false,portfolioPublic:true},
  {id:'david',displayName:'David Okoro',username:'daveodds',initials:'DO',bio:'Sports modeler. Closing-line value over hot takes.',specialization:['Sports'],followers:5440,following:390,accuracy:69,performance:-1.8,consistency:77,contrarian:47,isFollowing:false,portfolioPublic:false},
  {id:'nora',displayName:'Nora Wells',username:'noraw',initials:'NW',bio:'Public sentiment and political forecasting.',specialization:['Macro','Markets'],followers:11210,following:517,accuracy:75,performance:5.6,consistency:84,contrarian:83,isFollowing:false,portfolioPublic:true}
];

const ago=(m:number)=>new Date(Date.now()-m*60000).toISOString();
export const initialPosts: Post[] = [
  {id:'p-current-1',authorId:'current',content:'My first public portfolio snapshot. Performance is visible; total wallet value stays private.',createdAt:ago(8),portfolio:[{symbol:'BTC',name:'Bitcoin',entry:74920,current:84520,performance:12.8,allocation:46},{symbol:'SOL',name:'Solana',entry:132,current:166.5,performance:26.1,allocation:21}],likes:34,replies:6,reposts:2,liked:false,saved:false,reposted:false},
  {id:'p1',authorId:'sarah',content:'Bitcoin still looks stronger than the market is pricing. Exchange supply keeps falling while institutional flows remain constructive.',createdAt:ago(12),marketId:'bitcoin-2026',likes:248,replies:31,reposts:18,liked:false,saved:false,reposted:false},
  {id:'p2',authorId:'marcus',content:'A loss is still part of the thesis. ETH has not worked yet, and I am keeping the original entry public.',createdAt:ago(34),position:{symbol:'ETH',name:'Ethereum',entry:2770,current:2569,performance:-7.26,allocation:24},likes:84,replies:19,reposts:3,liked:false,saved:false,reposted:false},
  {id:'p3',authorId:'elena',content:'PredictAI and my on-chain read are aligned here, but macro remains the reason I am sizing carefully.',createdAt:ago(58),marketId:'bitcoin-2026',ai:{probability:68,marketProbability:62,edge:6,confidence:'Medium',summary:'On-chain activity and price momentum remain constructive while macro conditions limit conviction.'},likes:412,replies:47,reposts:62,liked:false,saved:false,reposted:false},
  {id:'p4',authorId:'amina',content:'Henan are priced too aggressively after the lineup update. The draw is more live than the headline probability suggests.',createdAt:ago(82),marketId:'henan',likes:193,replies:26,reposts:14,liked:false,saved:false,reposted:false},
  {id:'p5',authorId:'michael',content:'Long-duration election markets are useful, but today’s certainty is mostly narrative. I care more about how probabilities react to new entrants.',createdAt:ago(130),likes:121,replies:18,reposts:9,liked:false,saved:false,reposted:false},
  {id:'p6',authorId:'sarah',content:'Monthly public snapshot. SOL led; ETH detracted. Nothing hidden because the losing position matters too.',createdAt:ago(190),portfolio:[{symbol:'BTC',name:'Bitcoin',entry:74920,current:84520,performance:12.8,allocation:46},{symbol:'ETH',name:'Ethereum',entry:2770,current:2569,performance:-7.26,allocation:24}],likes:536,replies:72,reposts:41,liked:false,saved:false,reposted:false},
  {id:'p7',authorId:'nora',content:'The 2028 nominee market is underweighting coalition-building. Name recognition is not the same as delegate strength.',createdAt:ago(330),marketId:'dem-2028',likes:287,replies:43,reposts:29,liked:false,saved:false,reposted:false}
];

export const defaultWalletSettings: WalletSettings = {requireBiometrics:true,withdrawalConfirmation:true,autoLock:'5 min',trustedAddresses:[],defaultNetwork:'Polygon',withdrawalLimit:'1000',feeSpeed:'Standard',transactionNotifications:true,currency:'USD',hideBalances:false,assetSort:'Balance',compactView:false,walletMode:'Prediction',supportedAssets:{USDC:true,USDT:true},connectedWallet:null};
export const defaultPrivacy: PrivacySettings = {publicProfile:true,showPortfolioPerformance:true,showTotalPortfolioValue:false,showHoldings:true,showPositionHistory:true,showLikedPosts:false,showFollowingList:true,allowLeaderboards:true,allowSearch:true};
export const initialNotifications: Notification[] = [
  {id:'movement',title:'Bitcoin probability moved',message:'↑ 85,000 is now trading at 62%, up 6 points today.',time:'12 min ago',group:'Today',kind:'market',read:false},
  {id:'social',title:'Sarah Kim followed you',message:'Your public market commentary has a new follower.',time:'1 hr ago',group:'Today',kind:'social',read:false},
  {id:'deposit',title:'Deposit address ready',message:'Your Polygon USDC deposit address is ready to use.',time:'Yesterday',group:'Earlier',kind:'wallet',read:true},
  {id:'security',title:'Security preferences updated',message:'Biometric approval is enabled for withdrawals.',time:'2 days ago',group:'Earlier',kind:'security',read:true},
  {id:'welcome',title:'Welcome to PredictAI',message:'Discover events, make responsible predictions, and follow results in real time.',time:'3 days ago',group:'Earlier',kind:'market',read:true}
];

export const depositAddresses: Record<WalletSettings['defaultNetwork'],string> = {Ethereum:'0x7B42eF91A06C8d31a8F5927B09cE41D67A2f9021',Polygon:'0x91A8c3F702d4E65B71c9A20F6bE58D1243A76c0B',Arbitrum:'0xC46f71D3908a5E21bA794d30E6c7F8A214B65e09',Base:'0xE12A68c90B4F7d351A6eD20C9F83B47A50D162fe'};
