import { Ionicons } from '@expo/vector-icons';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors } from '../../theme/colors';
import type { ComposerDraft } from '../../types/social';
import { AIAnalysisShareCard } from '../components/AIAnalysisShareCard';
import { PublicPortfolioCard } from '../components/PublicPortfolioCard';
import { PublicPositionCard } from '../components/PublicPositionCard';
import { QuotedPostCard } from '../components/QuotedPostCard';
import { SocialAvatar } from '../components/SocialAvatar';
import { SocialMarketCard } from '../components/SocialMarketCard';

const tools = [
  { key: 'market', label: 'Market', icon: 'analytics-outline' },
  { key: 'position', label: 'Position', icon: 'trending-up-outline' },
  { key: 'portfolio', label: 'Portfolio', icon: 'pie-chart-outline' },
  { key: 'ai', label: 'PredictAI', icon: 'sparkles-outline' },
] as const;

export function CreatePostScreen({ draft, onAddAI, onAddMarket, onAddPortfolio, onAddPosition, onCancel, onChange, onOpenMarket, onPost }: { draft: ComposerDraft; onAddAI: () => void; onAddMarket: () => void; onAddPortfolio: () => void; onAddPosition: () => void; onCancel: () => void; onChange: (draft: ComposerDraft) => void; onOpenMarket: (marketId: string) => void; onPost: () => void }) {
  const valid = !!draft.content.trim() || !!(draft.marketId || draft.position || draft.portfolio || draft.aiAnalysis || draft.quotePostId);
  const removeAttachment = () => onChange({ content: draft.content });
  const choose = (key: (typeof tools)[number]['key']) => key === 'market' ? onAddMarket() : key === 'position' ? onAddPosition() : key === 'portfolio' ? onAddPortfolio() : onAddAI();
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.root}><View style={styles.header}><Pressable onPress={onCancel}><Text style={styles.cancel}>Cancel</Text></Pressable><Text style={styles.title}>New Post</Text><Pressable disabled={!valid} onPress={onPost} style={[styles.post, !valid && styles.disabled]}><Text style={[styles.postText, !valid && styles.disabledText]}>Post</Text></Pressable></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.composer}><SocialAvatar initials="PK" size={38} /><TextInput autoFocus maxLength={500} multiline onChangeText={(content) => onChange({ ...draft, content })} placeholder="Share your market view..." placeholderTextColor={colors.textMuted} style={styles.input} textAlignVertical="top" value={draft.content} /></View>{draft.content.length >= 440 ? <Text style={[styles.counter, draft.content.length >= 490 && styles.counterDanger]}>{500 - draft.content.length}</Text> : null}{draft.marketId || draft.position || draft.portfolio || draft.aiAnalysis || draft.quotePostId ? <View style={styles.attachment}><Pressable accessibilityLabel="Remove attachment" hitSlop={8} onPress={removeAttachment} style={styles.remove}><Ionicons color={colors.text} name="close" size={16} /></Pressable>{draft.aiAnalysis ? <AIAnalysisShareCard analysis={draft.aiAnalysis} marketId={draft.marketId} /> : draft.position ? <PublicPositionCard position={draft.position} /> : draft.portfolio ? <PublicPortfolioCard portfolio={draft.portfolio} /> : draft.marketId ? <SocialMarketCard marketId={draft.marketId} onOpen={() => onOpenMarket(draft.marketId!)} /> : draft.quotePostId ? <QuotedPostCard postId={draft.quotePostId} /> : null}</View> : null}<Text style={styles.addLabel}>Add to your post</Text><View style={styles.tools}>{tools.map((tool) => <Pressable accessibilityLabel={`Add ${tool.label}`} key={tool.key} onPress={() => choose(tool.key)} style={({ pressed }) => [styles.tool, pressed && styles.pressed]}><View style={styles.toolIcon}><Ionicons color={tool.key === 'ai' ? colors.accent : colors.text} name={tool.icon} size={18} /></View><Text style={styles.toolText}>{tool.label}</Text></Pressable>)}</View><View style={styles.notice}><Ionicons color={colors.textMuted} name="information-circle-outline" size={15} /><Text style={styles.noticeText}>Share only information you want public. Wallet addresses and private account details are never attached.</Text></View></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, header: { height: 52, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border }, cancel: { color: colors.text, fontSize: 11 }, title: { color: colors.text, fontSize: 15, fontWeight: '600' }, post: { minWidth: 52, borderRadius: 8, backgroundColor: colors.button, paddingHorizontal: 12, paddingVertical: 7, alignItems: 'center' }, postText: { color: colors.buttonText, fontSize: 10, fontWeight: '700' }, disabled: { backgroundColor: colors.surface }, disabledText: { color: colors.textFaint }, content: { padding: 15, paddingBottom: 40 }, composer: { flexDirection: 'row', alignItems: 'flex-start', gap: 11 }, input: { minHeight: 115, flex: 1, color: colors.text, fontSize: 14, lineHeight: 20, paddingTop: 7 }, counter: { color: colors.textMuted, fontSize: 9, textAlign: 'right' }, counterDanger: { color: colors.danger }, attachment: { position: 'relative', marginTop: 8 }, remove: { position: 'absolute', zIndex: 2, top: 5, right: 5, width: 25, height: 25, borderRadius: 13, backgroundColor: 'rgba(0,0,0,.7)', alignItems: 'center', justifyContent: 'center' }, addLabel: { color: colors.textMuted, fontSize: 9, fontWeight: '700', textTransform: 'uppercase', letterSpacing: .6, marginTop: 25 }, tools: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 11 }, tool: { alignItems: 'center', gap: 6 }, toolIcon: { width: 42, height: 38, borderRadius: 10, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, toolText: { color: colors.textMuted, fontSize: 8 }, pressed: { opacity: .6 }, notice: { marginTop: 28, padding: 11, borderRadius: 10, backgroundColor: '#17191B', flexDirection: 'row', alignItems: 'flex-start', gap: 8 }, noticeText: { flex: 1, color: colors.textFaint, fontSize: 8, lineHeight: 13 } });
