import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { ProfilePhotoAvatar } from '../../components/ProfilePhotoAvatar';
import { getCurrentUser, updateCurrentUser } from '../../services/social';
import { colors } from '../../theme/colors';
import { SocialScreenHeader } from '../components/SocialScreenHeader';

export function EditPublicProfileScreen({ onBack, onSaved }: { onBack: () => void; onSaved: () => void }) {
  const current = getCurrentUser(); const [name, setName] = useState(current.displayName); const [username, setUsername] = useState(current.username); const [bio, setBio] = useState(current.bio); const [tags, setTags] = useState(current.specialization.join(', '));
  const save = () => { const cleanName = name.trim(); const clean = username.trim().replace(/^@/, '').replace(/\s/g, ''); if (!cleanName || !clean) { Alert.alert('Complete your profile', 'Name and username are required.'); return; } updateCurrentUser({ displayName: cleanName, username: clean, bio: bio.trim(), specialization: tags.split(',').map((tag) => tag.trim()).filter(Boolean).slice(0, 5) }); onSaved(); };
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.root}><SocialScreenHeader action="Save" onAction={save} onBack={onBack} title="Edit public profile"/><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.avatar}><ProfilePhotoAvatar editable initials={current.initials} size={72}/><Text style={styles.change}>Tap the photo to change or remove it</Text></View><Field label="Display name" onChangeText={setName} value={name}/><Field autoCapitalize="none" label="Username" onChangeText={setUsername} prefix="@" value={username}/><Field label="Bio" multiline onChangeText={setBio} value={bio}/><Field label="Specializations" multiline onChangeText={setTags} value={tags}/><Text style={styles.hint}>Separate specializations with commas. Add up to five topics.</Text></ScrollView></KeyboardAvoidingView>;
}
function Field({ label, prefix, ...props }: React.ComponentProps<typeof TextInput> & { label: string; prefix?: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><View style={styles.inputRow}>{prefix ? <Text style={styles.prefix}>{prefix}</Text> : null}<TextInput {...props} maxLength={props.multiline ? 180 : 40} placeholderTextColor={colors.textFaint} style={[styles.input, props.multiline && styles.multiline]}/></View></View>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, content: { padding: 16 }, avatar: { alignItems: 'center', marginVertical: 16 }, change: { color: colors.textMuted, fontSize: 11, marginTop: 10 }, field: { marginTop: 16 }, label: { color: colors.textMuted, fontSize: 9, marginBottom: 7 }, inputRow: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 10, backgroundColor: '#151719', paddingHorizontal: 12 }, prefix: { color: colors.textMuted, fontSize: 12 }, input: { flex: 1, color: colors.text, fontSize: 12, minHeight: 43, paddingVertical: 10 }, multiline: { minHeight: 88, textAlignVertical: 'top' }, hint: { color: colors.textFaint, fontSize: 8, marginTop: 8 } });
