import { useMemo, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { getPrivacySettings, getSuggestedUsers, getSocialUser } from '../../services/social';
import { colors } from '../../theme/colors';
import { SocialScreenHeader } from '../components/SocialScreenHeader';
import { SocialUserRow } from '../components/SocialUserRow';

export function FollowersFollowingScreen({ initialTab, onBack, onOpenProfile, userId }: { initialTab: 'followers' | 'following'; onBack: () => void; onOpenProfile: (id: string) => void; userId: string }) {
  const [tab, setTab] = useState(initialTab); const [query, setQuery] = useState(''); const [version, setVersion] = useState(0); const owner = getSocialUser(userId);
  const followingPrivate = !!owner?.isCurrentUser && tab === 'following' && !getPrivacySettings().showFollowingList;
  const users = useMemo(() => { if (followingPrivate) return []; const all = getSuggestedUsers(); const source = tab === 'following' ? all.filter((user) => user.isFollowing).concat(all.filter((user) => !user.isFollowing)) : [...all].reverse(); const value = query.trim().toLowerCase(); return value ? source.filter((user) => `${user.displayName} ${user.username}`.toLowerCase().includes(value)) : source; }, [followingPrivate, query, tab, version]);
  return <View style={styles.root}><SocialScreenHeader onBack={onBack} title={owner?.displayName ?? 'Connections'}/><View style={styles.tabs}><Pressable onPress={() => setTab('followers')} style={[styles.tab, tab === 'followers' && styles.active]}><Text style={[styles.tabText, tab === 'followers' && styles.activeText]}>Followers {owner?.followers ?? 0}</Text></Pressable><Pressable onPress={() => setTab('following')} style={[styles.tab, tab === 'following' && styles.active]}><Text style={[styles.tabText, tab === 'following' && styles.activeText]}>Following {owner?.following ?? 0}</Text></Pressable></View>{followingPrivate ? <Text style={styles.private}>This following list is private.</Text> : <><TextInput onChangeText={setQuery} placeholder="Search people" placeholderTextColor={colors.textFaint} style={styles.search} value={query}/><FlatList data={users} extraData={version} keyExtractor={(item) => item.id} ListEmptyComponent={<Text style={styles.empty}>No people found.</Text>} renderItem={({ item }) => <SocialUserRow onChanged={() => setVersion((v) => v + 1)} onOpen={() => onOpenProfile(item.id)} user={item}/>} /></>}</View>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, tabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: colors.border }, tab: { flex: 1, padding: 13, alignItems: 'center' }, active: { borderBottomWidth: 2, borderBottomColor: colors.text }, tabText: { color: colors.textMuted, fontSize: 10 }, activeText: { color: colors.text, fontWeight: '700' }, search: { margin: 12, height: 39, borderRadius: 10, backgroundColor: colors.surface, color: colors.text, paddingHorizontal: 13, fontSize: 10 }, empty: { color: colors.textMuted, textAlign: 'center', padding: 35, fontSize: 10 }, private: { color: colors.textMuted, fontSize: 10, textAlign: 'center', padding: 38 } });
