import { useEffect, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { followUser, getLeaderboard, unfollowUser } from '../../services/social';
import { colors } from '../../theme/colors';
import type { LeaderboardType, SocialUser } from '../../types/social';
import { formatPercent, formatProbability } from '../../utils/socialFormatters';
import { SocialAvatar } from '../components/SocialAvatar';
import { SocialScreenHeader } from '../components/SocialScreenHeader';

const tabs: { key: LeaderboardType; label: string }[] = [{ key: 'accuracy', label: 'Accuracy' }, { key: 'performance', label: '30D' }, { key: 'consistency', label: 'Consistency' }, { key: 'contrarian', label: 'Contrarian' }];
const metric = (user: SocialUser, type: LeaderboardType) => type === 'accuracy' ? formatProbability(user.predictionAccuracy ?? 0, 1) : type === 'performance' ? formatPercent(user.performance30d ?? 0, 1) : type === 'consistency' ? `${user.consistency ?? 0}/100` : `${user.contrarianScore ?? 0}/100`;
export function LeaderboardScreen({ onBack, onOpenProfile }: { onBack: () => void; onOpenProfile: (id: string) => void }) {
  const [type, setType] = useState<LeaderboardType>('accuracy'); const [users, setUsers] = useState<SocialUser[]>([]); const [version, setVersion] = useState(0);
  useEffect(() => { void getLeaderboard(type).then((items) => setUsers(items.map((item) => ({ ...item })))); }, [type, version]);
  const toggleFollow = async (user: SocialUser) => { user.isFollowing ? await unfollowUser(user.id) : await followUser(user.id); setVersion((value) => value + 1); };
  return <View style={styles.root}><SocialScreenHeader onBack={onBack} title="Leaderboard"/><View style={styles.tabs}>{tabs.map((tab) => <Pressable key={tab.key} onPress={() => setType(tab.key)} style={[styles.tab, type === tab.key && styles.activeTab]}><Text style={[styles.tabText, type === tab.key && styles.activeText]}>{tab.label}</Text></Pressable>)}</View><Text style={styles.note}>Rankings use public, resolved activity. Returns are not guarantees of future results.</Text><FlatList data={users} keyExtractor={(item) => item.id} renderItem={({ item, index }) => <View style={styles.row}><Pressable onPress={() => onOpenProfile(item.id)} style={styles.person}><Text style={[styles.rank, index < 3 && styles.top]}>#{index + 1}</Text><SocialAvatar initials={item.initials}/><View style={styles.identity}><Text style={styles.name}>{item.displayName}</Text><Text style={styles.handle}>@{item.username} · {item.marketsCalled ?? 0} markets</Text></View></Pressable><View style={styles.result}><Text style={[styles.metric, type === 'performance' && (item.performance30d ?? 0) < 0 && styles.negative]}>{metric(item, type)}</Text><Text style={styles.secondary}>{item.bestCategory ?? 'Markets'}</Text></View>{item.isCurrentUser ? <Text style={styles.you}>You</Text> : <Pressable onPress={() => void toggleFollow(item)} style={[styles.follow, item.isFollowing && styles.following]}><Text style={[styles.followText, item.isFollowing && styles.followingText]}>{item.isFollowing ? 'Following' : 'Follow'}</Text></Pressable>}</View>} /></View>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, tabs: { flexDirection: 'row', paddingHorizontal: 10, borderBottomWidth: 1, borderBottomColor: colors.border }, tab: { flex: 1, paddingVertical: 12, alignItems: 'center' }, activeTab: { borderBottomWidth: 2, borderBottomColor: colors.text }, tabText: { color: colors.textMuted, fontSize: 8 }, activeText: { color: colors.text, fontWeight: '700' }, note: { color: colors.textMuted, fontSize: 8, lineHeight: 13, padding: 12 }, row: { flexDirection: 'row', alignItems: 'center', padding: 12, gap: 8, borderBottomWidth: 1, borderBottomColor: colors.border }, person: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 }, rank: { width: 23, color: colors.textMuted, fontSize: 10, fontWeight: '700' }, top: { color: colors.accent }, identity: { flex: 1 }, name: { color: colors.text, fontSize: 10, fontWeight: '700' }, handle: { color: colors.textMuted, fontSize: 7, marginTop: 3 }, result: { alignItems: 'flex-end' }, metric: { color: colors.accent, fontSize: 10, fontWeight: '800' }, secondary: { color: colors.textMuted, fontSize: 7, marginTop: 3 }, negative: { color: colors.danger }, follow: { minWidth: 49, alignItems: 'center', paddingHorizontal: 7, paddingVertical: 7, borderRadius: 7, backgroundColor: colors.button }, following: { backgroundColor: 'transparent', borderWidth: 1, borderColor: colors.border }, followText: { color: colors.buttonText, fontSize: 7, fontWeight: '700' }, followingText: { color: colors.text }, you: { minWidth: 49, textAlign: 'center', color: colors.textMuted, fontSize: 8, fontWeight: '700' } });
