import { Ionicons } from '@expo/vector-icons';
import { useEffect, useMemo, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { markets } from '../../services/marketData';
import { getMarketPosts } from '../../services/social';
import { colors } from '../../theme/colors';
import type { SocialPost } from '../../types/social';
import { ConsensusComparisonCard } from '../components/ConsensusComparisonCard';
import { SocialPostCard } from '../components/SocialPostCard';
import { SocialScreenHeader } from '../components/SocialScreenHeader';

export function MarketPostsScreen({ marketId, onBack, onCreate, onOpenAnalysis, onOpenMarket, onOpenPortfolio, onOpenPost, onOpenProfile, onQuote }: { marketId: string; onBack: () => void; onCreate: (marketId: string) => void; onOpenAnalysis: (id: string) => void; onOpenMarket: (id: string) => void; onOpenPortfolio: (id: string) => void; onOpenPost: (id: string) => void; onOpenProfile: (id: string) => void; onQuote: (id: string) => void }) {
  const market = markets.find((item) => item.id === marketId); const [posts, setPosts] = useState<SocialPost[]>([]); const [latest, setLatest] = useState(false); const [version, setVersion] = useState(0);
  useEffect(() => { void getMarketPosts(marketId).then(setPosts); }, [marketId, version]);
  const sorted = useMemo(() => latest ? [...posts].sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt)) : [...posts].sort((a, b) => b.likes + b.replies - a.likes - a.replies), [latest, posts]);
  const probability = market?.outcomes[0]?.probability ?? 50; const community = Math.max(4, Math.min(96, Math.round(probability + (posts.length % 2 ? -6 : 4)))); const ai = Math.max(4, Math.min(96, Math.round(probability + 3)));
  const neutral = 18; const bearish = Math.max(0, 100 - community - neutral);
  const header = <><View style={styles.marketHeader}><Text style={styles.category}>{market?.category ?? 'Market'} discussion</Text><Text style={styles.title}>{market?.title ?? 'Market posts'}</Text><View style={styles.actions}><Pressable onPress={() => onOpenMarket(marketId)} style={styles.outline}><Text style={styles.outlineText}>View market</Text></Pressable><Pressable onPress={() => onCreate(marketId)} style={styles.primary}><Ionicons color={colors.buttonText} name="create-outline" size={14}/><Text style={styles.primaryText}>Post</Text></Pressable></View></View><View style={styles.community}><Text style={styles.communityTitle}>Community view</Text><View style={styles.sentiment}><View><Text style={styles.sentimentLabel}>Bullish</Text><Text style={styles.bullish}>{community}%</Text></View><View><Text style={styles.sentimentLabel}>Neutral</Text><Text style={styles.neutral}>{neutral}%</Text></View><View><Text style={styles.sentimentLabel}>Bearish</Text><Text style={styles.bearish}>{bearish}%</Text></View></View></View><View style={styles.consensus}><ConsensusComparisonCard ai={ai} community={community} market={probability}/></View><View style={styles.filter}><Text style={styles.count}>{posts.length} community posts</Text><View style={styles.segment}><Pressable onPress={() => setLatest(false)} style={[styles.segmentButton, !latest && styles.segmentActive]}><Text style={[styles.segmentText, !latest && styles.segmentTextActive]}>Top</Text></Pressable><Pressable onPress={() => setLatest(true)} style={[styles.segmentButton, latest && styles.segmentActive]}><Text style={[styles.segmentText, latest && styles.segmentTextActive]}>Latest</Text></Pressable></View></View></>;
  return <View style={styles.root}><SocialScreenHeader actionIcon="analytics-outline" onAction={() => onOpenAnalysis(marketId)} onBack={onBack} title="Market posts"/><FlatList data={sorted} keyExtractor={(item) => item.id} ListEmptyComponent={<Text style={styles.empty}>Be the first to share an insight on this market.</Text>} ListHeaderComponent={header} renderItem={({ item }) => <SocialPostCard onChanged={() => setVersion((v) => v + 1)} onComment={() => onOpenPost(item.id)} onOpenAnalysis={onOpenAnalysis} onOpenMarket={onOpenMarket} onOpenPortfolio={onOpenPortfolio} onOpenPost={onOpenPost} onOpenProfile={onOpenProfile} onQuote={onQuote} post={item}/>} /></View>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, marketHeader: { padding: 15 }, category: { color: colors.accent, fontSize: 8, fontWeight: '700', textTransform: 'uppercase' }, title: { color: colors.text, fontSize: 17, lineHeight: 23, fontWeight: '700', marginTop: 6 }, actions: { flexDirection: 'row', gap: 8, marginTop: 14 }, outline: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: 9, borderWidth: 1, borderColor: colors.border }, outlineText: { color: colors.text, fontSize: 9, fontWeight: '700' }, primary: { flex: 1, flexDirection: 'row', gap: 5, justifyContent: 'center', alignItems: 'center', borderRadius: 9, backgroundColor: colors.button }, primaryText: { color: colors.buttonText, fontSize: 9, fontWeight: '700' }, community: { marginHorizontal: 15, marginBottom: 10, borderRadius: 12, padding: 12, backgroundColor: '#17191B' }, communityTitle: { color: colors.text, fontSize: 10, fontWeight: '700' }, sentiment: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 }, sentimentLabel: { color: colors.textMuted, fontSize: 7, textTransform: 'uppercase' }, bullish: { color: colors.accent, fontSize: 15, fontWeight: '800', marginTop: 3 }, neutral: { color: '#A9ABB1', fontSize: 15, fontWeight: '800', marginTop: 3 }, bearish: { color: colors.danger, fontSize: 15, fontWeight: '800', marginTop: 3 }, consensus: { marginHorizontal: 15, marginBottom: 12 }, filter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 13, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.border }, count: { color: colors.textMuted, fontSize: 9 }, segment: { flexDirection: 'row', padding: 2, borderRadius: 7, backgroundColor: colors.surface }, segmentButton: { paddingHorizontal: 11, paddingVertical: 6, borderRadius: 6 }, segmentActive: { backgroundColor: '#3B3D42' }, segmentText: { color: colors.textMuted, fontSize: 8 }, segmentTextActive: { color: colors.text, fontWeight: '700' }, empty: { color: colors.textMuted, fontSize: 10, textAlign: 'center', padding: 40 } });
