import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { PrimaryButton } from '../../components/PrimaryButton';
import { getShareablePositions } from '../../services/social';
import { colors } from '../../theme/colors';
import type { PublicPosition } from '../../types/social';
import { PublicPositionCard } from '../components/PublicPositionCard';

function Toggle({ label, onChange, value }: { label: string; onChange: (value: boolean) => void; value: boolean }) { return <View style={styles.toggle}><Text style={styles.toggleLabel}>{label}</Text><Switch onValueChange={onChange} thumbColor={value ? colors.buttonText : '#AAA'} trackColor={{ false: '#35383E', true: colors.accent }} value={value} /></View>; }
export function PositionShareBuilderScreen({ onAdd, onBack }: { onAdd: (position: PublicPosition) => void; onBack: () => void }) {
  const positions = getShareablePositions();
  const [selected, setSelected] = useState(positions[0]!);
  const update = (values: Partial<PublicPosition>) => setSelected((current) => ({ ...current, ...values }));
  return <View style={styles.root}><View style={styles.header}><Pressable onPress={onBack}><Ionicons color={colors.text} name="chevron-back" size={25} /></Pressable><Text style={styles.title}>Share position</Text><View style={styles.spacer} /></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.intro}>You decide what people can see.</Text><View style={styles.selector}>{positions.map((position) => <Pressable key={position.id} onPress={() => setSelected({ ...position })} style={[styles.asset, selected.id === position.id && styles.assetSelected]}><Text style={[styles.assetText, selected.id === position.id && styles.assetTextSelected]}>{position.assetSymbol}</Text></Pressable>)}</View><Text style={styles.sectionTitle}>Public preview</Text><PublicPositionCard position={selected} /><Text style={styles.sectionTitle}>Visible information</Text><View style={styles.settings}><Toggle label="Show performance %" onChange={(showPerformance) => update({ showPerformance })} value={selected.showPerformance} /><Toggle label="Show entry price" onChange={(showEntryPrice) => update({ showEntryPrice })} value={selected.showEntryPrice} /><Toggle label="Show current price" onChange={(showCurrentPrice) => update({ showCurrentPrice })} value={selected.showCurrentPrice} /><Toggle label="Show position value" onChange={(showPositionValue) => update({ showPositionValue })} value={selected.showPositionValue} /><Toggle label="Show entry date" onChange={(showEntryDate) => update({ showEntryDate })} value={!!selected.showEntryDate} /><Toggle label="Show portfolio allocation" onChange={(showAllocation) => update({ showAllocation })} value={!!selected.showAllocation} /></View><Text style={styles.privacy}>Private wallet and transaction information is never included.</Text><View style={styles.submit}><PrimaryButton label="Add to post" onPress={() => onAdd(selected)} /></View></ScrollView></View>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, header: { height: 52, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { color: colors.text, fontSize: 16, fontWeight: '600' }, spacer: { width: 25 }, content: { padding: 15, paddingBottom: 40 }, intro: { color: colors.textMuted, fontSize: 11 }, selector: { flexDirection: 'row', gap: 8, marginTop: 15 }, asset: { flex: 1, paddingVertical: 10, borderRadius: 9, backgroundColor: colors.surface, alignItems: 'center' }, assetSelected: { backgroundColor: '#2B3A17', borderWidth: 1, borderColor: colors.accent }, assetText: { color: colors.textMuted, fontSize: 10, fontWeight: '700' }, assetTextSelected: { color: colors.accent }, sectionTitle: { color: colors.text, fontSize: 12, fontWeight: '700', marginTop: 24, marginBottom: 9 }, settings: { borderRadius: 12, backgroundColor: '#181A1D', paddingHorizontal: 13 }, toggle: { minHeight: 54, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.border }, toggleLabel: { flex: 1, color: colors.text, fontSize: 11 }, privacy: { color: colors.textFaint, fontSize: 8, lineHeight: 13, marginTop: 13 }, submit: { marginTop: 22 } });
