import { Ionicons } from '@expo/vector-icons';
import { useEffect, useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { addReply, getPost, getReplies, likeReply } from '../../services/social';
import { colors } from '../../theme/colors';
import type { SocialPost, SocialReply } from '../../types/social';
import { formatCompactNumber, formatSocialTime } from '../../utils/socialFormatters';
import { SocialAvatar } from '../components/SocialAvatar';
import { SocialPostCard } from '../components/SocialPostCard';

export function PostDetailScreen({ onBack, onChanged, onOpenAnalysis, onOpenMarket, onOpenPortfolio, onOpenPost, onOpenProfile, onQuote, postId, version }: { onBack: () => void; onChanged: () => void; onOpenAnalysis: (marketId: string) => void; onOpenMarket: (marketId: string) => void; onOpenPortfolio: (userId: string) => void; onOpenPost: (id: string) => void; onOpenProfile: (id: string) => void; onQuote: (id: string) => void; postId: string; version: number }) {
  const [post, setPost] = useState<SocialPost | null>(null); const [replies, setReplies] = useState<SocialReply[]>([]); const [text, setText] = useState(''); const inputRef = useRef<TextInput>(null);
  const load = async () => { setPost(await getPost(postId)); setReplies(await getReplies(postId)); };
  useEffect(() => { void load(); }, [postId, version]);
  const send = async () => { if (!text.trim()) return; await addReply(postId, text); setText(''); await load(); onChanged(); };
  const toggleReplyLike = async (reply: SocialReply) => { await likeReply(reply.id, !reply.liked); await load(); };
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.root}><View style={styles.header}><Pressable onPress={onBack}><Ionicons color={colors.text} name="chevron-back" size={25}/></Pressable><Text style={styles.headerTitle}>Post</Text><View style={styles.spacer}/></View><ScrollView showsVerticalScrollIndicator={false}>{post ? <><SocialPostCard expanded onChanged={() => { void load(); onChanged(); }} onComment={() => inputRef.current?.focus()} onOpenAnalysis={onOpenAnalysis} onOpenMarket={onOpenMarket} onOpenPortfolio={onOpenPortfolio} onOpenPost={onOpenPost} onOpenProfile={onOpenProfile} onQuote={onQuote} post={post}/><Text style={styles.engagement}>{formatCompactNumber(post.likes)} likes · {formatCompactNumber(post.replies)} replies · {formatCompactNumber(post.reposts)} reposts</Text><Text style={styles.repliesTitle}>Replies</Text>{replies.map((reply) => <View key={reply.id} style={styles.reply}><Pressable onPress={() => onOpenProfile(reply.author.id)}><SocialAvatar initials={reply.author.initials} size={32}/></Pressable><View style={styles.replyCopy}><Text style={styles.replyAuthor}>{reply.author.displayName} <Text style={styles.replyMeta}>@{reply.author.username} · {formatSocialTime(reply.createdAt)}</Text></Text>{reply.replyingTo ? <Text style={styles.replying}>Replying to @{reply.replyingTo}</Text> : null}<Text style={styles.replyText}>{reply.content}</Text><View style={styles.replyActions}><Pressable accessibilityLabel={reply.liked ? 'Unlike reply' : 'Like reply'} onPress={() => void toggleReplyLike(reply)} style={styles.replyAction}><Ionicons color={reply.liked ? colors.positive : colors.textMuted} name={reply.liked ? 'heart' : 'heart-outline'} size={14}/><Text style={styles.replyCount}>{reply.likes}</Text></Pressable><Pressable onPress={() => { setText(`@${reply.author.username} `); inputRef.current?.focus(); }} style={styles.replyAction}><Ionicons color={colors.textMuted} name="return-down-forward-outline" size={14}/><Text style={styles.replyCount}>Reply</Text></Pressable></View></View></View>)}</> : <Text style={styles.loading}>Loading post…</Text>}</ScrollView><View style={styles.composer}><SocialAvatar initials="PK" size={31}/><TextInput ref={inputRef} multiline onChangeText={setText} placeholder="Post your reply..." placeholderTextColor={colors.textMuted} style={styles.input} value={text}/><Pressable accessibilityLabel="Send reply" disabled={!text.trim()} onPress={() => void send()}><Ionicons color={text.trim() ? colors.accent : colors.textFaint} name="send" size={20}/></Pressable></View></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, header: { height: 52, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border }, headerTitle: { color: colors.text, fontSize: 16, fontWeight: '600' }, spacer: { width: 25 }, engagement: { color: colors.textMuted, fontSize: 9, paddingHorizontal: 15, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.border }, repliesTitle: { color: colors.text, fontSize: 13, fontWeight: '700', padding: 15 }, reply: { flexDirection: 'row', gap: 9, paddingHorizontal: 15, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.border }, replyCopy: { flex: 1 }, replyAuthor: { color: colors.text, fontSize: 10, fontWeight: '700' }, replyMeta: { color: colors.textMuted, fontWeight: '400' }, replying: { color: colors.textMuted, fontSize: 8, marginTop: 4 }, replyText: { color: colors.text, fontSize: 11, lineHeight: 17, marginTop: 6 }, replyActions: { flexDirection: 'row', alignItems: 'center', gap: 16, marginTop: 8 }, replyAction: { flexDirection: 'row', alignItems: 'center', gap: 5 }, replyCount: { color: colors.textMuted, fontSize: 8 }, composer: { minHeight: 58, paddingHorizontal: 13, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: '#131517', borderTopWidth: 1, borderTopColor: colors.border }, input: { flex: 1, maxHeight: 80, color: colors.text, fontSize: 11, backgroundColor: colors.surface, borderRadius: 18, paddingHorizontal: 13, paddingVertical: 8 }, loading: { color: colors.textMuted, textAlign: 'center', marginTop: 50 } });
