import { Ionicons } from '@expo/vector-icons';
import { useCallback, useEffect, useState } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { getFeed, getSuggestedUsers } from '../../services/social';
import { colors } from '../../theme/colors';
import type { SocialFeedType, SocialPost } from '../../types/social';
import { SocialFeedSkeleton } from '../components/SocialFeedSkeleton';
import { SocialPostCard } from '../components/SocialPostCard';
import { SocialUserRow } from '../components/SocialUserRow';

const tabs: { key: SocialFeedType; label: string }[] = [{ key: 'for_you', label: 'For You' }, { key: 'following', label: 'Following' }, { key: 'trending', label: 'Trending' }];

export function PostsScreen({ onCreate, onLeaderboard, onOpenAnalysis, onOpenMarket, onOpenPortfolio, onOpenPost, onOpenProfile, onQuote, onSearch, version }: { onCreate: () => void; onLeaderboard: () => void; onOpenAnalysis: (marketId: string) => void; onOpenMarket: (marketId: string) => void; onOpenPortfolio: (userId: string) => void; onOpenPost: (id: string) => void; onOpenProfile: (id: string) => void; onQuote: (id: string) => void; onSearch: () => void; version: number }) {
  const [feed, setFeed] = useState<SocialFeedType>('for_you');
  const [posts, setPosts] = useState<SocialPost[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [failed, setFailed] = useState(false);
  const [localVersion, setLocalVersion] = useState(0);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); setFailed(false); try { setPosts(await getFeed(feed)); } catch { setFailed(true); } finally { setLoading(false); setRefreshing(false); } }, [feed]);
  useEffect(() => { void load(); }, [load, version, localVersion]);
  const changed = () => setLocalVersion((current) => current + 1);
  const empty = feed === 'following' ? <View style={styles.empty}><Ionicons color={colors.textMuted} name="people-outline" size={32} /><Text style={styles.emptyTitle}>Your feed is quiet</Text><Text style={styles.emptyText}>Follow analysts and traders to see their posts here.</Text><Pressable onPress={onSearch} style={styles.find}><Text style={styles.findText}>Find people</Text></Pressable><Text style={styles.suggestionsTitle}>People you may want to follow</Text><View style={styles.suggestions}>{getSuggestedUsers().slice(0, 3).map((user) => <SocialUserRow key={user.id} onChanged={changed} onOpen={() => onOpenProfile(user.id)} user={user} />)}</View></View> : <View style={styles.empty}><Text style={styles.emptyTitle}>No posts available</Text></View>;
  const header = <><View style={styles.header}><Text style={styles.title}>Posts</Text><View style={styles.headerActions}><Pressable accessibilityLabel="Search posts" onPress={onSearch} style={styles.headerAction}><Ionicons color={colors.text} name="search-outline" size={22}/></Pressable><Pressable accessibilityLabel="Open leaderboard" onPress={onLeaderboard} style={styles.headerAction}><Ionicons color={colors.text} name="trophy-outline" size={22}/></Pressable></View></View><View style={styles.tabs}>{tabs.map((tab) => <Pressable key={tab.key} onPress={() => setFeed(tab.key)} style={styles.tab}><Text style={[styles.tabText, feed === tab.key && styles.tabTextActive]}>{tab.label}</Text>{feed === tab.key ? <View style={styles.tabIndicator}/> : null}</Pressable>)}</View>{failed ? <View style={styles.error}><Text style={styles.errorTitle}>Couldn't load posts.</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Try again</Text></Pressable></View> : null}</>;
  if (loading) return <View style={styles.root}>{header}<SocialFeedSkeleton /></View>;
  return <View style={styles.root}><FlatList contentContainerStyle={styles.list} data={failed ? [] : posts} keyExtractor={(item) => item.id} ListEmptyComponent={empty} ListHeaderComponent={header} refreshControl={<RefreshControl colors={[colors.accent]} onRefresh={() => void load(true)} refreshing={refreshing} tintColor={colors.accent} />} renderItem={({ item }) => <SocialPostCard onChanged={changed} onComment={() => onOpenPost(item.id)} onOpenAnalysis={onOpenAnalysis} onOpenMarket={onOpenMarket} onOpenPortfolio={onOpenPortfolio} onOpenPost={onOpenPost} onOpenProfile={onOpenProfile} onQuote={onQuote} post={item} showFollow={feed !== 'following'} />} showsVerticalScrollIndicator={false} /><Pressable accessibilityLabel="Create post" onPress={onCreate} style={({ pressed }) => [styles.fab, pressed && styles.fabPressed]}><Ionicons color={colors.buttonText} name="add" size={27} /></Pressable></View>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, list: { paddingBottom: 86 }, header: { height: 56, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.background }, title: { color: colors.text, fontSize: 20, fontWeight: '700' }, headerActions: { flexDirection: 'row', gap: 8 }, headerAction: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center' }, tabs: { height: 44, flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: colors.border, backgroundColor: colors.background }, tab: { flex: 1, alignItems: 'center', justifyContent: 'flex-end' }, tabText: { color: colors.textMuted, fontSize: 13, fontWeight: '500' }, tabTextActive: { color: colors.text, fontWeight: '600' }, tabIndicator: { width: 28, height: 2, borderRadius: 1, backgroundColor: colors.text, marginTop: 10 }, fab: { position: 'absolute', right: 17, bottom: 16, width: 52, height: 52, borderRadius: 26, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center', elevation: 4 }, fabPressed: { opacity: .72, transform: [{ scale: .97 }] }, empty: { padding: 40, alignItems: 'center' }, emptyTitle: { color: colors.text, fontSize: 17, fontWeight: '600', marginTop: 12 }, emptyText: { color: colors.textMuted, fontSize: 13, textAlign: 'center', lineHeight: 19, marginTop: 8 }, find: { marginTop: 16, borderRadius: 8, backgroundColor: colors.button, paddingHorizontal: 18, paddingVertical: 10 }, findText: { color: colors.buttonText, fontSize: 12, fontWeight: '600' }, suggestionsTitle: { alignSelf: 'flex-start', color: colors.text, fontSize: 15, fontWeight: '600', marginTop: 32 }, suggestions: { alignSelf: 'stretch', marginTop: 8 }, error: { padding: 12, backgroundColor: '#2B1B1E', flexDirection: 'row', justifyContent: 'space-between' }, errorTitle: { color: colors.danger, fontSize: 12 }, retry: { color: colors.text, fontSize: 12, fontWeight: '600' } });
