import { Ionicons } from '@expo/vector-icons';
import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { followUser, getPrivacySettings, getUser, getUserPosts, unfollowUser } from '../../services/social';
import { colors } from '../../theme/colors';
import type { SocialPost, SocialUser } from '../../types/social';
import { formatCompactNumber, formatPercent, formatProbability } from '../../utils/socialFormatters';
import { PublicPortfolioCard } from '../components/PublicPortfolioCard';
import { PublicPositionCard } from '../components/PublicPositionCard';
import { SocialAvatar } from '../components/SocialAvatar';
import { SocialPostCard } from '../components/SocialPostCard';
import { SocialScreenHeader } from '../components/SocialScreenHeader';

type ProfileTab = 'posts' | 'positions' | 'portfolio';
export function TraderProfileScreen({ onBack, onEdit, onFollowers, onFollowing, onOpenAnalysis, onOpenMarket, onOpenPortfolio, onOpenPost, onOpenProfile, onPrivacy, onQuote, onSaved, userId }: { onBack: () => void; onEdit: () => void; onFollowers: () => void; onFollowing: () => void; onOpenAnalysis: (id: string) => void; onOpenMarket: (id: string) => void; onOpenPortfolio: (id: string) => void; onOpenPost: (id: string) => void; onOpenProfile: (id: string) => void; onPrivacy: () => void; onQuote: (id: string) => void; onSaved: () => void; userId: string }) {
  const [user, setUser] = useState<SocialUser | null>(null); const [posts, setPosts] = useState<SocialPost[]>([]); const [tab, setTab] = useState<ProfileTab>('posts'); const [performanceRange, setPerformanceRange] = useState<'7D' | '30D' | '3M' | 'All'>('30D'); const [version, setVersion] = useState(0);
  useEffect(() => { void Promise.all([getUser(userId), getUserPosts(userId)]).then(([nextUser, nextPosts]) => { setUser(nextUser ? { ...nextUser } : null); setPosts(nextPosts); }); }, [userId, version]);
  const positions = useMemo(() => posts.flatMap((post) => post.position ? [post.position] : post.portfolio?.positions ?? []), [posts]); const portfolio = posts.find((post) => post.portfolio)?.portfolio; const privacy = getPrivacySettings();
  if (!user) return <View style={styles.root}><SocialScreenHeader onBack={onBack} title="Profile"/><Text style={styles.empty}>Loading profile…</Text></View>;
  const toggleFollow = async () => { user.isFollowing ? await unfollowUser(user.id) : await followUser(user.id); setVersion((v) => v + 1); };
  const menu = () => user.isCurrentUser ? Alert.alert('Profile options', 'Manage your public social presence.', [{ text: 'Saved posts', onPress: onSaved }, { text: 'Privacy settings', onPress: onPrivacy }, { text: 'Cancel', style: 'cancel' }]) : Alert.alert('Profile options', `Manage interactions with @${user.username}.`, [{ text: 'Mute', onPress: () => Alert.alert('Muted', `You will see fewer posts from @${user.username}.`) }, { text: 'Report', style: 'destructive', onPress: () => Alert.alert('Report received', 'Thanks. Our moderation team will review this profile.') }, { text: 'Cancel', style: 'cancel' }]);
  const profileHeader = <><View style={styles.hero}><View style={styles.top}><SocialAvatar initials={user.initials} size={68}/><Pressable onPress={user.isCurrentUser ? onEdit : () => void toggleFollow()} style={[styles.follow, user.isFollowing && styles.following]}><Text style={[styles.followText, user.isFollowing && styles.followingText]}>{user.isCurrentUser ? 'Edit profile' : user.isFollowing ? 'Following' : 'Follow'}</Text></Pressable></View><Text style={styles.name}>{user.displayName}</Text><Text style={styles.handle}>@{user.username}</Text><Text style={styles.bio}>{user.bio}</Text><View style={styles.tags}>{user.specialization.map((tag) => <View key={tag} style={styles.tag}><Text style={styles.tagText}>{tag}</Text></View>)}</View><View style={styles.connections}><Pressable onPress={onFollowing}><Text style={styles.connection}><Text style={styles.connectionValue}>{formatCompactNumber(user.following)}</Text> Following</Text></Pressable><Pressable onPress={onFollowers}><Text style={styles.connection}><Text style={styles.connectionValue}>{formatCompactNumber(user.followers)}</Text> Followers</Text></Pressable></View></View><View style={styles.metrics}><Metric label="Accuracy" value={formatProbability(user.predictionAccuracy ?? 0, 1)}/><Metric label="30D return" negative={(user.performance30d ?? 0) < 0} value={formatPercent(user.performance30d ?? 0, 1)}/><Metric label="Consistency" value={`${user.consistency ?? 0}/100`}/><Metric label="Markets called" value={`${user.marketsCalled ?? 0}`}/></View><View style={styles.performance}><View style={styles.performanceHeading}><Text style={styles.performanceTitle}>Public performance · {performanceRange}</Text><Text style={[styles.performanceValue, (user.performance30d ?? 0) < 0 && styles.negative]}>{formatPercent(user.performance30d ?? 0, 1)}</Text></View><View style={styles.spark}>{[14, 18, 16, 24, 21, 31, 29, 38, 35, 45, 42, 51].map((height, index) => <View key={index} style={[styles.bar, { height }, (user.performance30d ?? 0) < 0 && styles.negativeBar]}/>)}</View><View style={styles.ranges}>{(['7D', '30D', '3M', 'All'] as const).map((range) => <Pressable key={range} onPress={() => setPerformanceRange(range)} style={[styles.range, performanceRange === range && styles.rangeActive]}><Text style={[styles.rangeText, performanceRange === range && styles.rangeTextActive]}>{range}</Text></Pressable>)}</View></View><View style={styles.tabs}>{(['posts', 'positions', 'portfolio'] as ProfileTab[]).map((item) => <Pressable key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && styles.tabActive]}><Text style={[styles.tabText, tab === item && styles.tabTextActive]}>{item.charAt(0).toUpperCase() + item.slice(1)}</Text></Pressable>)}</View></>;
  if (user.isCurrentUser && !privacy.publicProfile) return <View style={styles.root}><SocialScreenHeader actionIcon="ellipsis-horizontal" onAction={menu} onBack={onBack} title="Profile"/><View style={styles.private}><Ionicons color={colors.textMuted} name="lock-closed-outline" size={30}/><Text style={styles.privateTitle}>Your public profile is off</Text><Pressable onPress={onPrivacy} style={styles.follow}><Text style={styles.followText}>Review privacy</Text></Pressable></View></View>;
  const positionsVisible = !user.isCurrentUser || privacy.showPositionHistory;
  const portfolioVisible = !user.isCurrentUser || privacy.showPortfolioPerformance;
  const renderTab = () => tab === 'positions' ? <View style={styles.tabContent}>{positionsVisible ? positions.length ? positions.slice(0, 8).map((position, index) => <PublicPositionCard key={`${position.id}-${index}`} position={position}/>) : <Text style={styles.empty}>No public positions yet.</Text> : <Text style={styles.empty}>This position history is private.</Text>}</View> : tab === 'portfolio' ? <View style={styles.tabContent}>{portfolioVisible ? portfolio ? <PublicPortfolioCard onOpen={() => onOpenPortfolio(user.id)} portfolio={{ ...portfolio, positions: user.isCurrentUser && !privacy.showHoldings ? [] : portfolio.positions, showTotalValue: portfolio.showTotalValue && (!user.isCurrentUser || privacy.showTotalPortfolioValue) }}/> : <Text style={styles.empty}>No portfolio snapshot shared.</Text> : <Text style={styles.empty}>This portfolio is private.</Text>}</View> : null;
  return <View style={styles.root}><SocialScreenHeader actionIcon="ellipsis-horizontal" onAction={menu} onBack={onBack} title="Profile"/>{tab === 'posts' ? <FlatList data={posts} keyExtractor={(item) => item.id} ListEmptyComponent={<Text style={styles.empty}>No posts yet.</Text>} ListHeaderComponent={profileHeader} renderItem={({ item }) => <SocialPostCard onChanged={() => setVersion((v) => v + 1)} onComment={() => onOpenPost(item.id)} onOpenAnalysis={onOpenAnalysis} onOpenMarket={onOpenMarket} onOpenPortfolio={onOpenPortfolio} onOpenPost={onOpenPost} onOpenProfile={onOpenProfile} onQuote={onQuote} post={item}/>} /> : <ScrollView>{profileHeader}{renderTab()}</ScrollView>}</View>;
}
function Metric({ label, negative, value }: { label: string; negative?: boolean; value: string }) { return <View style={styles.metric}><Text style={[styles.metricValue, negative && styles.negative]}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, hero: { padding: 16 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, follow: { paddingHorizontal: 16, paddingVertical: 9, borderRadius: 9, backgroundColor: colors.button }, following: { backgroundColor: 'transparent', borderWidth: 1, borderColor: colors.border }, followText: { color: colors.buttonText, fontSize: 9, fontWeight: '700' }, followingText: { color: colors.text }, name: { color: colors.text, fontSize: 18, fontWeight: '800', marginTop: 12 }, handle: { color: colors.textMuted, fontSize: 10, marginTop: 2 }, bio: { color: colors.text, fontSize: 11, lineHeight: 17, marginTop: 11 }, tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 11 }, tag: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 12, backgroundColor: colors.surface }, tagText: { color: colors.textMuted, fontSize: 8 }, connections: { flexDirection: 'row', gap: 18, marginTop: 14 }, connection: { color: colors.textMuted, fontSize: 9 }, connectionValue: { color: colors.text, fontWeight: '700' }, metrics: { flexDirection: 'row', paddingVertical: 13, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.border }, metric: { flex: 1, alignItems: 'center', paddingHorizontal: 3 }, metricValue: { color: colors.accent, fontSize: 12, fontWeight: '800' }, negative: { color: colors.danger }, metricLabel: { color: colors.textMuted, fontSize: 7, marginTop: 4, textAlign: 'center' }, performance: { padding: 15 }, performanceHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, performanceTitle: { color: colors.textMuted, fontSize: 9 }, performanceValue: { color: colors.accent, fontSize: 12, fontWeight: '800' }, spark: { height: 54, flexDirection: 'row', alignItems: 'flex-end', gap: 5, marginTop: 10, borderBottomWidth: 1, borderBottomColor: colors.border }, bar: { flex: 1, backgroundColor: '#6C9529', borderRadius: 2 }, negativeBar: { backgroundColor: '#923948' }, ranges: { flexDirection: 'row', marginTop: 10, padding: 2, backgroundColor: '#17191B', borderRadius: 7 }, range: { flex: 1, alignItems: 'center', paddingVertical: 6, borderRadius: 6 }, rangeActive: { backgroundColor: colors.surface }, rangeText: { color: colors.textMuted, fontSize: 8 }, rangeTextActive: { color: colors.text, fontWeight: '700' }, tabs: { flexDirection: 'row', borderBottomWidth: 1, borderColor: colors.border }, tab: { flex: 1, alignItems: 'center', paddingVertical: 12 }, tabActive: { borderBottomWidth: 2, borderBottomColor: colors.text }, tabText: { color: colors.textMuted, fontSize: 9 }, tabTextActive: { color: colors.text, fontWeight: '700' }, tabContent: { padding: 15, paddingBottom: 40 }, empty: { color: colors.textMuted, fontSize: 10, textAlign: 'center', padding: 35 }, private: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 }, privateTitle: { color: colors.text, fontSize: 14, fontWeight: '700' } });
