import type { Market } from '../types/market';

const sportsRules = `This market resolves using the official result after the first 90 minutes of regular play plus stoppage time. If the game is postponed, the market remains open until the game is completed. If the game is cancelled without a replacement, it resolves according to the published market policy.\n\nThe primary resolution source is the official statistics published by the governing body or event organizer. If official statistics are unavailable, a consensus of credible reporting may be used.`;
const standardRules = `This market resolves to “Yes” if the listed price is reached through 11:59 PM ET on the final day of the year specified in the title. Price action before this market's creation is not considered.\n\nThe resolution source for crypto price markets is the BTC/USDT or ETH/USDT high and low price published by the named exchange using one-minute candles. Prices from other exchanges or trading pairs are not considered.\n\nFor event markets, the primary resolution source is the official announcement from the organization responsible for the event. If no official result is available, a consensus of credible reporting may be used.`;

export const markets: Market[] = [
  { id: 'dem-2028', title: 'Democratic Presidential Nominee 2028', category: 'Recommend', subcategory: 'Hot', volume: '$1.27B', more: 49, outcomes: [{ label: 'Alexandria Ocasio-Cortez', odds: '4.78x', probability: 21 }, { label: 'Jon Ossoff', odds: '6.75x', probability: 15 }], rules: standardRules },
  { id: 'president-2028', title: 'Presidential Election Winner 2028', category: 'Recommend', subcategory: 'Hot', volume: '$693.1M', more: 50, outcomes: [{ label: 'JD Vance', odds: '4.28x', probability: 23 }, { label: 'Alexandria Ocasio-Cortez', odds: '7.06x', probability: 14 }], rules: standardRules },
  { id: 'rep-2028', title: 'Republican Presidential Nominee 2028', category: 'Recommend', subcategory: 'Hot', volume: '$691.7M', more: 40, outcomes: [{ label: 'J.D. Vance', odds: '2.11x', probability: 47 }, { label: 'Marco Rubio', odds: '5.15x', probability: 19 }], rules: standardRules },
  { id: 'henan', title: 'Wuhan San Zhen FC vs. Henan FC', category: 'Sports', subcategory: 'Soccer', volume: '$1.74K', more: 1, outcomes: [{ label: 'Henan FC', odds: '1.14x', probability: 87, color: '#1677ff' }, { label: 'Draw (Wuhan San Zhen FC vs. Henan FC)', odds: '1.28x', probability: 78, color: '#ff7b3b' }, { label: 'Wuhan San Zhen FC', odds: '10.00x', probability: 10, color: '#43c6d5' }], rules: sportsRules },
  { id: 'birmingham', title: 'Birmingham Legion FC vs. New Mexico United', category: 'Sports', subcategory: 'Soccer', volume: '$6.13K', more: 1, outcomes: [{ label: 'New Mexico United', odds: '33.33x', probability: 3 }, { label: 'Draw (Birmingham vs. New Mexico)', odds: '100.00x', probability: 1 }], rules: sportsRules },
  { id: 'bitcoin-2026', title: 'What price will Bitcoin hit in 2026?', category: 'Crypto', subcategory: 'Target Price', volume: '$59.88M', more: 43, outcomes: [{ label: '↓ 75,000', odds: '1.11x', probability: 90, color: '#1677ff' }, { label: '↓ 70,000', odds: '1.47x', probability: 68, color: '#ff7b3b' }, { label: '↑ 85,000', odds: '1.51x', probability: 66, color: '#43c6d5' }, { label: '↑ 90,000', odds: '2.17x', probability: 46, color: '#9e91ee' }], rules: standardRules },
  { id: 'bitcoin-august', title: 'What price will Bitcoin hit in August?', category: 'Crypto', subcategory: 'Target Price', volume: '$21.99M', more: 21, outcomes: [{ label: '↓ 77,500', odds: '1.25x', probability: 80 }, { label: '↑ 80,000', odds: '1.53x', probability: 65 }], rules: standardRules },
  { id: 'ethereum-2026', title: 'What price will Ethereum hit in 2026?', category: 'Crypto', subcategory: 'Target Price', volume: '$12.69M', more: 21, outcomes: [{ label: '↓ 2,250', odds: '1.29x', probability: 78 }, { label: '↑ 2,750', odds: '1.49x', probability: 67 }], rules: standardRules },
];
