import type { PublicPortfolioSnapshot, PublicPosition, SocialPost, SocialPrivacySettings, SocialReply, SocialUser } from '../types/social';

export const socialUsers: SocialUser[] = [
  { id: 'current', displayName: 'Peter Kingsley', username: 'peterk', initials: 'PK', bio: 'Prediction markets, crypto and transparent public thinking.', specialization: ['Markets', 'AI'], followers: 284, following: 96, predictionAccuracy: 64, performance30d: 4.8, consistency: 71, contrarianScore: 58, marketsCalled: 31, bestCategory: 'Crypto', isFollowing: false, isCurrentUser: true, portfolioPublic: true },
  { id: 'sarah', displayName: 'Sarah Kim', username: 'sarahk', initials: 'SK', bio: 'Crypto + macro. Publishing the thesis before the outcome.', specialization: ['Crypto', 'Macro'], followers: 12840, following: 243, predictionAccuracy: 78, performance30d: 18.4, consistency: 86, contrarianScore: 74, marketsCalled: 84, bestCategory: 'Crypto', isFollowing: true, portfolioPublic: true },
  { id: 'marcus', displayName: 'Marcus Reed', username: 'marcusreads', initials: 'MR', bio: 'Risk-first crypto trader. Wins and losses stay public.', specialization: ['Crypto'], followers: 4210, following: 310, predictionAccuracy: 66, performance30d: -3.7, consistency: 73, contrarianScore: 61, marketsCalled: 49, bestCategory: 'Crypto', isFollowing: true, portfolioPublic: true },
  { id: 'amina', displayName: 'Amina Bello', username: 'aminab', initials: 'AB', bio: 'Football markets and lineup-driven probabilities.', specialization: ['Sports'], followers: 7860, following: 188, predictionAccuracy: 74, performance30d: 9.2, consistency: 82, contrarianScore: 52, marketsCalled: 117, bestCategory: 'Sports', isFollowing: true, portfolioPublic: false },
  { id: 'michael', displayName: 'Michael Chen', username: 'mchen', initials: 'MC', bio: 'Macro regimes, elections, and long-duration markets.', specialization: ['Macro', 'Markets'], followers: 9620, following: 402, predictionAccuracy: 72, performance30d: 6.1, consistency: 80, contrarianScore: 79, marketsCalled: 96, bestCategory: 'Politics', isFollowing: false, portfolioPublic: true },
  { id: 'tobi', displayName: 'Tobi Adeyemi', username: 'tobiforecasts', initials: 'TA', bio: 'Emerging analyst focused on election forecasting.', specialization: ['Markets'], followers: 631, following: 184, predictionAccuracy: 61, performance30d: 2.4, consistency: 65, contrarianScore: 68, marketsCalled: 18, bestCategory: 'Politics', isFollowing: false, portfolioPublic: false },
  { id: 'elena', displayName: 'Elena Rossi', username: 'elenar', initials: 'ER', bio: 'On-chain research and liquidity conditions.', specialization: ['Crypto', 'AI'], followers: 15430, following: 221, predictionAccuracy: 76, performance30d: 13.7, consistency: 88, contrarianScore: 71, marketsCalled: 102, bestCategory: 'Crypto', isFollowing: false, portfolioPublic: true },
  { id: 'david', displayName: 'David Okoro', username: 'daveodds', initials: 'DO', bio: 'Sports modeler. Closing-line value over hot takes.', specialization: ['Sports'], followers: 5440, following: 390, predictionAccuracy: 69, performance30d: -1.8, consistency: 77, contrarianScore: 47, marketsCalled: 143, bestCategory: 'Sports', isFollowing: false, portfolioPublic: false },
  { id: 'nora', displayName: 'Nora Wells', username: 'noraw', initials: 'NW', bio: 'Public sentiment and political forecasting.', specialization: ['Macro', 'Markets'], followers: 11210, following: 517, predictionAccuracy: 75, performance30d: 5.6, consistency: 84, contrarianScore: 83, marketsCalled: 131, bestCategory: 'Politics', isFollowing: false, portfolioPublic: true },
  { id: 'jules', displayName: 'Jules Martin', username: 'julesm', initials: 'JM', bio: 'Learning in public across crypto and sports.', specialization: ['Crypto', 'Sports'], followers: 418, following: 302, predictionAccuracy: 57, performance30d: -6.2, consistency: 60, contrarianScore: 55, marketsCalled: 14, bestCategory: 'Sports', isFollowing: false, portfolioPublic: true },
];

const user = (id: string) => socialUsers.find((item) => item.id === id)!;
const position = (id: string, symbol: string, name: string, entry: number, current: number, allocation = 30): PublicPosition => ({ id, assetSymbol: symbol, assetName: name, entryPrice: entry, currentPrice: current, performancePercent: (current / entry - 1) * 100, allocationPercent: allocation, entryDate: 'Aug 3, 2026', showEntryPrice: true, showCurrentPrice: true, showPerformance: true, showPositionValue: false, showEntryDate: false, showAllocation: false });

export const publicPositions = {
  btc: position('btc-public', 'BTC', 'Bitcoin', 74920, 84520, 46),
  ethLoss: position('eth-loss', 'ETH', 'Ethereum', 2770, 2569, 24),
  sol: position('sol-public', 'SOL', 'Solana', 132, 166.5, 21),
  sports: { id: 'sports-call', assetSymbol: 'HEN', assetName: 'Henan FC', entryPrice: 1.18, currentPrice: 1.08, performancePercent: 8.47, showEntryPrice: true, showCurrentPrice: true, showPerformance: true, showPositionValue: false } satisfies PublicPosition,
};

export const samplePortfolio: PublicPortfolioSnapshot = { timeframe: '30D', performancePercent: 18.42, positions: [publicPositions.btc, publicPositions.sol, publicPositions.ethLoss], wins: 7, losses: 3, showPerformance: true, showBestWorst: true, showWinLoss: true, showTotalValue: false, showAllocation: false, showChart: true };
export const losingPortfolio: PublicPortfolioSnapshot = { timeframe: '30D', performancePercent: -6.22, positions: [publicPositions.ethLoss, { ...publicPositions.btc, performancePercent: -2.1 }], wins: 2, losses: 5, showPerformance: true, showBestWorst: true, showWinLoss: true, showTotalValue: false, showAllocation: false, showChart: true };

const at = (minutesAgo: number) => new Date(Date.now() - minutesAgo * 60_000).toISOString();
const base = { liked: false, saved: false, reposted: false };

export const socialPosts: SocialPost[] = [
  { ...base, id: 'p-current-1', author: user('current'), type: 'portfolio', content: 'My first public portfolio snapshot. Performance is visible; total wallet value stays private.', createdAt: at(8), portfolio: { ...samplePortfolio, performancePercent: 4.8, wins: 4, losses: 2 }, likes: 34, replies: 6, reposts: 2 },
  { ...base, id: 'p-current-2', author: user('current'), type: 'insight', content: 'I am using Posts to keep a public record of the reasoning behind each market view—not just the outcomes.', createdAt: at(10), likes: 27, replies: 4, reposts: 1 },
  { ...base, id: 'p1', author: user('sarah'), type: 'market', content: 'Bitcoin still looks stronger than the market is pricing. Exchange supply keeps falling while institutional flows remain constructive.', createdAt: at(12), marketId: 'bitcoin-2026', likes: 248, replies: 31, reposts: 18, performanceSincePosted: 4.8 },
  { ...base, id: 'p2', author: user('marcus'), type: 'position', content: 'A loss is still part of the thesis. ETH has not worked yet, and I am keeping the original entry public.', createdAt: at(34), position: publicPositions.ethLoss, likes: 84, replies: 19, reposts: 3, performanceSincePosted: -3.1 },
  { ...base, id: 'p3', author: user('elena'), type: 'ai_analysis', content: 'PredictAI and my on-chain read are aligned here, but macro remains the reason I am sizing carefully.', createdAt: at(58), marketId: 'bitcoin-2026', aiAnalysis: { probability: 68, marketProbability: 62, edge: 6, verdict: 'lean_yes', confidence: 'medium', summary: 'On-chain activity and price momentum remain constructive while macro conditions limit conviction.' }, likes: 412, replies: 47, reposts: 62, performanceSincePosted: 2.6 },
  { ...base, id: 'p4', author: user('amina'), type: 'market', content: 'Henan are priced too aggressively after the lineup update. The draw is more live than the headline probability suggests.', createdAt: at(82), marketId: 'henan', likes: 193, replies: 26, reposts: 14, performanceSincePosted: 1.7 },
  { ...base, id: 'p5', author: user('michael'), type: 'insight', content: 'Long-duration election markets are useful, but today’s certainty is mostly narrative. I care more about how probabilities react to new entrants.', createdAt: at(130), likes: 121, replies: 18, reposts: 9 },
  { ...base, id: 'p6', author: user('sarah'), type: 'portfolio', content: 'Monthly public snapshot. SOL led; ETH detracted. Nothing hidden because the losing position matters too.', createdAt: at(190), portfolio: samplePortfolio, likes: 536, replies: 72, reposts: 41 },
  { ...base, id: 'p7', author: user('jules'), type: 'portfolio', content: 'Rough month, shared as-is. My position sizing was the bigger mistake than the directional calls.', createdAt: at(260), portfolio: losingPortfolio, likes: 97, replies: 36, reposts: 6 },
  { ...base, id: 'p8', author: user('nora'), type: 'market', content: 'The 2028 nominee market is underweighting coalition-building. Name recognition is not the same as delegate strength.', createdAt: at(330), marketId: 'dem-2028', likes: 287, replies: 43, reposts: 29, performanceSincePosted: 0.8 },
  { ...base, id: 'p9', author: user('david'), type: 'position', content: 'Closing this call with a small loss. The pre-match number was good; the result was not. Both facts can be true.', createdAt: at(410), position: { ...publicPositions.sports, performancePercent: -2.4 }, likes: 68, replies: 12, reposts: 2, performanceSincePosted: -2.4 },
  { ...base, id: 'p10', author: user('tobi'), type: 'insight', content: 'My first public forecast thread: tracking endorsements, fundraising, and state-level organization separately instead of forcing one composite score.', createdAt: at(510), likes: 45, replies: 11, reposts: 4 },
  { ...base, id: 'p11', author: user('elena'), type: 'position', content: 'BTC position update. I am publishing percentage performance, entry, and current price—not account value.', createdAt: at(680), position: publicPositions.btc, likes: 329, replies: 38, reposts: 22, performanceSincePosted: 8.4 },
  { ...base, id: 'p12', author: user('marcus'), type: 'market', content: 'The $90K path is plausible, but the current edge disappears quickly if liquidity weakens.', createdAt: at(790), marketId: 'bitcoin-2026', likes: 139, replies: 28, reposts: 11, performanceSincePosted: -0.9 },
  { ...base, id: 'p13', author: user('amina'), type: 'insight', content: 'Sports forecasting credibility requires publishing before team news, then documenting what changed after team news.', createdAt: at(920), likes: 177, replies: 21, reposts: 16 },
  { ...base, id: 'p14', author: user('michael'), type: 'ai_analysis', content: 'Interesting disagreement: the model is slightly above this political market, while my view remains neutral until the field narrows.', createdAt: at(1100), marketId: 'president-2028', aiAnalysis: { probability: 29, marketProbability: 23, edge: 6, verdict: 'lean_yes', confidence: 'low', summary: 'Fundamentals are supportive, but the time horizon makes confidence low.' }, likes: 203, replies: 35, reposts: 19 },
  { ...base, id: 'p15', author: user('nora'), type: 'portfolio', content: 'Public markets portfolio: modest gains, low turnover, no account value disclosed.', createdAt: at(1350), portfolio: { ...samplePortfolio, performancePercent: 5.6, timeframe: '30D', positions: [publicPositions.btc, publicPositions.ethLoss] }, likes: 188, replies: 17, reposts: 8 },
  { ...base, id: 'p16', author: user('david'), type: 'market', content: 'New Mexico’s away price is too short for the available squad information. Waiting rather than forcing a call.', createdAt: at(1600), marketId: 'birmingham', likes: 74, replies: 9, reposts: 3 },
  { ...base, id: 'p17', author: user('tobi'), type: 'market', content: 'Marco Rubio at this probability deserves monitoring, not conviction. My watchlist trigger is organizational support.', createdAt: at(2100), marketId: 'rep-2028', likes: 61, replies: 14, reposts: 5 },
  { ...base, id: 'p18', author: user('jules'), type: 'position', content: 'SOL worked; ETH did not. Sharing both positions so the record reflects the whole portfolio.', createdAt: at(3100), position: publicPositions.sol, likes: 116, replies: 22, reposts: 7, performanceSincePosted: 5.2 },
  { ...base, id: 'p19', author: user('sarah'), type: 'market', content: 'August Bitcoin ranges are trading like certainty is higher than it is. Volatility can touch both sides.', createdAt: at(4500), marketId: 'bitcoin-august', likes: 265, replies: 39, reposts: 24 },
  { ...base, id: 'p20', author: user('elena'), type: 'market', content: 'Ethereum’s setup is improving, but relative strength still trails Bitcoin. That distinction matters for target markets.', createdAt: at(5900), marketId: 'ethereum-2026', likes: 218, replies: 30, reposts: 20, performanceSincePosted: -1.2 },
];

export const socialReplies: SocialReply[] = [
  { id: 'r1', postId: 'p1', author: user('michael'), content: 'The liquidity caveat matters. I would lower confidence before lowering direction.', createdAt: at(7), likes: 26, liked: false },
  { id: 'r2', postId: 'p1', author: user('tobi'), content: 'What would invalidate the exchange-supply signal for you?', createdAt: at(5), likes: 8, liked: false, replyingTo: 'sarahk' },
  { id: 'r3', postId: 'p2', author: user('sarah'), content: 'Keeping the original entry visible is exactly the right credibility signal.', createdAt: at(18), likes: 17, liked: false },
];

export const defaultSocialPrivacy: SocialPrivacySettings = { publicProfile: true, showPortfolioPerformance: true, showTotalPortfolioValue: false, showHoldings: true, showPositionHistory: true, showLikedPosts: false, showFollowingList: true, allowLeaderboards: true, allowSearch: true };
