import { Eye, EyeOff, Fingerprint, LockKeyhole, Mail, Phone, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { Button } from '../components/ui';
import { useApp } from '../store/AppStore';

function AuthShell({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <div className="auth-page"><section className="auth-showcase"><div className="auth-brand"><span className="brand-mark">P</span><strong>PredictAI</strong></div><div className="auth-message"><span className="eyebrow">Make the call</span><h1>Prediction markets, powered by intelligence.</h1><p>Research events, place responsible predictions, and build a public record of how you think.</p><div className="auth-proof"><span><ShieldCheck/> Secure wallet controls</span><span><Fingerprint/> Passkey-ready access</span></div></div><small>Independent desktop experience · Mobile apps available separately</small></section><section className="auth-panel"><div className="auth-card"><h2>{title}</h2><p>{description}</p>{children}</div></section></div>}

function useNext(){const location=useLocation();return new URLSearchParams(location.search).get('next')||'/app/predict';}
export function LoginPage(){const{session,login}=useApp();const navigate=useNavigate();const next=useNext();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[mode,setMode]=useState<'email'|'phone'>('email');const[visible,setVisible]=useState(false);const[error,setError]=useState('');if(session)return <Navigate to="/app/predict" replace/>;const submit=(e:React.FormEvent)=>{e.preventDefault();const valid=mode==='email'?/^\S+@\S+\.\S+$/.test(email):email.replace(/\D/g,'').length>=7;if(!valid||password.length<8){setError(mode==='email'?'Enter a valid email and a password of at least 8 characters.':'Enter a valid phone number and a password of at least 8 characters.');return;}login(email);navigate(next,{replace:true});};return <AuthShell title="Welcome back" description="Sign in to continue to your PredictAI workspace."><div className="segmented"><button className={mode==='email'?'active':''} onClick={()=>setMode('email')}><Mail/> Email</button><button className={mode==='phone'?'active':''} onClick={()=>setMode('phone')}><Phone/> Phone</button></div><form className="auth-form" onSubmit={submit}><label>{mode==='email'?'Email address':'Phone number'}<span className="field-with-icon">{mode==='email'?<Mail/>:<Phone/>}<input value={email} onChange={e=>setEmail(e.target.value)} type={mode==='email'?'email':'tel'} placeholder={mode==='email'?'you@example.com':'+234 000 000 0000'}/></span></label><label>Password<span className="field-with-icon"><LockKeyhole/><input value={password} onChange={e=>setPassword(e.target.value)} type={visible?'text':'password'} placeholder="At least 8 characters"/><button type="button" onClick={()=>setVisible(!visible)}>{visible?<EyeOff/>:<Eye/>}</button></span></label>{error&&<p className="form-error">{error}</p>}<div className="form-row"><Link to="/forgot-password">Forgot password?</Link></div><Button type="submit">Sign in</Button><button type="button" className="passkey" onClick={()=>setError('Passkey sign-in is not available for this prototype account. Use your password to continue.')}><Fingerprint/> Sign in with a passkey</button></form><p className="auth-switch">New to PredictAI? <Link to="/signup">Create an account</Link></p></AuthShell>}

export function SignupPage(){const navigate=useNavigate();const[email,setEmail]=useState('');const[referral,setReferral]=useState('');const[agree,setAgree]=useState(true);const[error,setError]=useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();if(!/^\S+@\S+\.\S+$/.test(email)||!agree){setError('Enter a valid email and accept the terms to continue.');return;}sessionStorage.setItem('predictai.signup.email',email);navigate('/password');};return <AuthShell title="Create your account" description="Start with your email, then secure your account."><form className="auth-form" onSubmit={submit}><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><details><summary>Have a referral code?</summary><label>Referral code<input value={referral} onChange={e=>setReferral(e.target.value)} placeholder="Optional"/></label></details><label className="check"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/><span>I agree to the Terms of Use and Privacy Policy.</span></label>{error&&<p className="form-error">{error}</p>}<Button type="submit">Continue</Button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></AuthShell>}

export function PasswordPage(){const{login}=useApp();const navigate=useNavigate();const email=sessionStorage.getItem('predictai.signup.email')||'';const[p1,setP1]=useState('');const[p2,setP2]=useState('');const[error,setError]=useState('');if(!email)return <Navigate to="/signup" replace/>;const submit=(e:React.FormEvent)=>{e.preventDefault();if(p1.length<8||p1!==p2){setError('Use at least 8 characters and make sure both passwords match.');return;}login(email);navigate('/app/predict');};return <AuthShell title="Secure your account" description={`Create a password for ${email}.`}><form className="auth-form" onSubmit={submit}><label>Password<input type="password" value={p1} onChange={e=>setP1(e.target.value)} placeholder="At least 8 characters"/></label><label>Confirm password<input type="password" value={p2} onChange={e=>setP2(e.target.value)} placeholder="Repeat password"/></label>{error&&<p className="form-error">{error}</p>}<Button type="submit">Create account</Button></form></AuthShell>}

export function ForgotPasswordPage(){const[email,setEmail]=useState('');const[sent,setSent]=useState(false);return <AuthShell title="Reset your password" description="We’ll send reset instructions if this email belongs to an account.">{sent?<div className="success-panel"><Mail/><h3>Check your inbox</h3><p>If an account exists for this email, reset instructions will be sent.</p><Link to="/login">Back to sign in</Link></div>:<form className="auth-form" onSubmit={e=>{e.preventDefault();if(/^\S+@\S+\.\S+$/.test(email))setSent(true);}}><label>Email address<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><Button type="submit">Send reset instructions</Button><Link className="center-link" to="/login">Back to sign in</Link></form>}</AuthShell>}
