import { Pressable, StyleSheet, Text, View } from 'react-native';
import { markets } from '../../services/marketData';
import { colors } from '../../theme/colors';
import type { SocialAIAnalysis } from '../../types/social';

const verdicts = { strong_yes: 'STRONG YES', lean_yes: 'LEAN YES', neutral: 'NEUTRAL', lean_no: 'LEAN NO', strong_no: 'STRONG NO' } as const;
export function AIAnalysisShareCard({ analysis, marketId, onOpen }: { analysis: SocialAIAnalysis; marketId?: string; onOpen?: () => void }) {
  const market = markets.find((item) => item.id === marketId);
  const content = <><Text style={styles.brand}>PredictAI Intelligence</Text><Text numberOfLines={2} style={styles.market}>{market?.title ?? 'Market intelligence report'}</Text><View style={styles.verdictRow}><Text style={styles.verdict}>{verdicts[analysis.verdict]}</Text><Text style={styles.confidence}>{analysis.confidence.toUpperCase()} CONFIDENCE</Text></View><View style={styles.metrics}><View><Text style={styles.label}>MARKET</Text><Text style={styles.value}>{analysis.marketProbability}%</Text></View><View><Text style={styles.label}>PREDICTAI</Text><Text style={styles.ai}>{analysis.probability}%</Text></View><View><Text style={styles.label}>EDGE</Text><Text style={styles.ai}>{analysis.edge >= 0 ? '+' : ''}{analysis.edge}%</Text></View></View>{analysis.summary ? <Text numberOfLines={3} style={styles.summary}>{analysis.summary}</Text> : null}{onOpen ? <Text style={styles.link}>View analysis →</Text> : null}</>;
  return onOpen ? <Pressable onPress={onOpen} style={({ pressed }) => [styles.card, pressed && styles.pressed]}>{content}</Pressable> : <View style={styles.card}>{content}</View>;
}
const styles = StyleSheet.create({ card: { marginTop: 11, borderRadius: 12, borderWidth: 1, borderColor: '#35451D', backgroundColor: '#182014', padding: 12 }, pressed: { opacity: .7 }, brand: { color: colors.accent, fontSize: 9, fontWeight: '800', letterSpacing: .4 }, market: { color: colors.text, fontSize: 12, lineHeight: 16, fontWeight: '600', marginTop: 7 }, verdictRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 }, verdict: { color: colors.text, fontSize: 10, fontWeight: '800' }, confidence: { color: colors.textMuted, fontSize: 8 }, metrics: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12, paddingTop: 10, borderTopWidth: 1, borderTopColor: '#304019' }, label: { color: colors.textMuted, fontSize: 7 }, value: { color: colors.text, fontSize: 16, fontWeight: '700', marginTop: 2 }, ai: { color: colors.accent, fontSize: 16, fontWeight: '700', marginTop: 2 }, summary: { color: colors.textMuted, fontSize: 9, lineHeight: 14, marginTop: 10 }, link: { color: colors.accent, fontSize: 9, fontWeight: '600', marginTop: 10 } });
