import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Alert, Modal, Pressable, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import { blockUser, deletePost, editPost, muteUser, savePost, unfollowUser } from '../../services/social';
import { colors } from '../../theme/colors';
import type { SocialPost } from '../../types/social';

function Option({ danger, icon, label, onPress }: { danger?: boolean; icon: keyof typeof Ionicons.glyphMap; label: string; onPress: () => void }) {
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.option, pressed && styles.pressed]}><Ionicons color={danger ? colors.danger : colors.text} name={icon} size={19} /><Text style={[styles.optionText, danger && styles.danger]}>{label}</Text></Pressable>;
}

export function PostOptionsSheet({ onChanged, onClose, post, visible }: { onChanged: () => void; onClose: () => void; post: SocialPost; visible: boolean }) {
  const [editing, setEditing] = useState(false); const [editText, setEditText] = useState(post.content);
  const closeAfter = (action: () => void | Promise<unknown>) => { void action(); onClose(); onChanged(); };
  const remove = () => Alert.alert('Delete post?', 'This removes the post from your public record. This action cannot be undone.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => closeAfter(() => deletePost(post.id)) }]);
  const report = () => Alert.alert('Report post', 'Why are you reporting this post?', ['Spam', 'Misleading', 'Harassment', 'Other', 'Cancel'].map((text) => ({ text, style: text === 'Cancel' ? 'cancel' as const : 'default' as const, onPress: text === 'Cancel' ? undefined : () => Alert.alert('Report received', 'Thank you. This post will be reviewed.') })));
  const block = () => Alert.alert(`Block @${post.author.username}?`, "You won't see each other's posts or profiles.", [{ text: 'Cancel', style: 'cancel' }, { text: 'Block', style: 'destructive', onPress: () => closeAfter(() => blockUser(post.author.id)) }]);
  const saveEdit = async () => { if (!editText.trim()) return; await editPost(post.id, editText); setEditing(false); onChanged(); };
  return <><Modal animationType="slide" onRequestClose={onClose} transparent visible={visible}><Pressable onPress={onClose} style={styles.overlay}><Pressable onPress={(event) => event.stopPropagation()} style={styles.sheet}><View style={styles.handle} /><Text style={styles.title}>Post actions</Text>{post.author.isCurrentUser ? <><Option icon="create-outline" label="Edit post" onPress={() => { setEditText(post.content); onClose(); setEditing(true); }} /><Option icon={post.saved ? 'bookmark' : 'bookmark-outline'} label={post.saved ? 'Remove from saved' : 'Save post'} onPress={() => closeAfter(() => savePost(post.id, !post.saved))} /><Option icon="share-outline" label="Share" onPress={() => { onClose(); void Share.share({ message: post.content }); }} /><Option danger icon="trash-outline" label="Delete" onPress={remove} /></> : <><Option icon={post.saved ? 'bookmark' : 'bookmark-outline'} label={post.saved ? 'Remove from saved' : 'Save post'} onPress={() => closeAfter(() => savePost(post.id, !post.saved))} /><Option icon="share-outline" label="Share" onPress={() => { onClose(); void Share.share({ message: `${post.author.displayName}: ${post.content}` }); }} /><Option icon="volume-mute-outline" label="Mute user" onPress={() => closeAfter(() => muteUser(post.author.id))} />{post.author.isFollowing ? <Option icon="person-remove-outline" label="Unfollow user" onPress={() => closeAfter(() => unfollowUser(post.author.id))} /> : null}<Option danger icon="flag-outline" label="Report" onPress={report} /><Option danger icon="ban-outline" label="Block" onPress={block} /></>}</Pressable></Pressable></Modal><Modal animationType="fade" onRequestClose={() => setEditing(false)} transparent visible={editing}><View style={styles.editOverlay}><View style={styles.editCard}><Text style={styles.title}>Edit post</Text><TextInput autoFocus maxLength={500} multiline onChangeText={setEditText} style={styles.editInput} value={editText}/><View style={styles.editActions}><Pressable onPress={() => setEditing(false)}><Text style={styles.cancel}>Cancel</Text></Pressable><Pressable disabled={!editText.trim()} onPress={() => void saveEdit()} style={styles.save}><Text style={styles.saveText}>Save</Text></Pressable></View></View></View></Modal></>;
}
const styles = StyleSheet.create({ overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.76)' }, sheet: { backgroundColor: '#191B1E', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 16, paddingBottom: 30 }, handle: { width: 48, height: 4, borderRadius: 2, backgroundColor: '#4A4D53', alignSelf: 'center', marginBottom: 17 }, title: { color: colors.text, fontSize: 16, fontWeight: '700', marginBottom: 8 }, option: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: colors.border }, optionText: { color: colors.text, fontSize: 12 }, danger: { color: colors.danger }, pressed: { opacity: .55 }, editOverlay: { flex: 1, justifyContent: 'center', padding: 22, backgroundColor: 'rgba(0,0,0,.8)' }, editCard: { borderRadius: 15, padding: 16, backgroundColor: '#191B1E' }, editInput: { minHeight: 110, color: colors.text, fontSize: 12, lineHeight: 18, textAlignVertical: 'top', borderRadius: 10, backgroundColor: colors.surface, padding: 12 }, editActions: { marginTop: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 20 }, cancel: { color: colors.textMuted, fontSize: 10 }, save: { backgroundColor: colors.button, borderRadius: 8, paddingHorizontal: 15, paddingVertical: 8 }, saveText: { color: colors.buttonText, fontSize: 10, fontWeight: '700' } });
