import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors } from '../../theme/colors';
import type { PublicPortfolioSnapshot } from '../../types/social';
import { formatPercent, formatPrice } from '../../utils/socialFormatters';

export function PublicPortfolioCard({ portfolio, onOpen }: { portfolio: PublicPortfolioSnapshot; onOpen?: () => void }) {
  const positive = portfolio.performancePercent >= 0; const ordered = [...portfolio.positions].sort((a, b) => b.performancePercent - a.performancePercent); const best = ordered[0]; const worst = ordered[ordered.length - 1];
  const content = <><View style={styles.heading}><Text style={styles.title}>{portfolio.timeframe} Portfolio</Text>{portfolio.showPerformance ? <Text style={[styles.performance, { color: positive ? colors.accent : colors.danger }]}>{formatPercent(portfolio.performancePercent, 2)}</Text> : null}</View>{portfolio.showChart ? <View style={styles.chart}>{[9, 14, 11, 20, 17, 25, 22, 31, 28, 38, 35, 43].map((height, index) => <View key={index} style={[styles.bar, { height }, !positive && styles.negativeBar]}/>)}</View> : null}<View style={styles.positions}>{portfolio.positions.slice(0, 5).map((position) => <View key={position.id} style={styles.row}><Text style={styles.symbol}>{position.assetSymbol}</Text>{portfolio.showAllocation && position.allocationPercent !== undefined ? <Text style={styles.value}>{position.allocationPercent}% allocated</Text> : portfolio.showPerformance ? <Text style={[styles.positionPerformance, { color: position.performancePercent >= 0 ? colors.accent : colors.danger }]}>{formatPercent(position.performancePercent)}</Text> : <Text style={styles.muted}>Shared holding</Text>}</View>)}</View>{portfolio.showBestWorst && best && worst ? <Text style={styles.record}>Best {best.assetSymbol} {formatPercent(best.performancePercent)} · Worst {worst.assetSymbol} {formatPercent(worst.performancePercent)}</Text> : null}{portfolio.showTotalValue && portfolio.totalValue ? <View style={styles.row}><Text style={styles.muted}>Public portfolio value</Text><Text style={styles.value}>{formatPrice(portfolio.totalValue)}</Text></View> : null}{portfolio.showWinLoss ? <Text style={styles.record}>{portfolio.wins} wins · {portfolio.losses} losses</Text> : null}{onOpen ? <Text style={styles.link}>View public portfolio →</Text> : null}</>;
  return onOpen ? <Pressable onPress={onOpen} style={({ pressed }) => [styles.card, pressed && styles.pressed]}>{content}</Pressable> : <View style={styles.card}>{content}</View>;
}
const styles = StyleSheet.create({ card: { marginTop: 11, borderRadius: 12, borderWidth: 1, borderColor: '#303237', backgroundColor: '#16181A', padding: 12 }, pressed: { opacity: .7 }, heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { color: colors.text, fontSize: 12, fontWeight: '700' }, performance: { fontSize: 18, fontWeight: '800' }, chart: { height: 47, marginTop: 11, flexDirection: 'row', alignItems: 'flex-end', gap: 4, borderBottomWidth: 1, borderBottomColor: colors.border }, bar: { flex: 1, maxWidth: 18, borderTopLeftRadius: 2, borderTopRightRadius: 2, backgroundColor: '#739F2B' }, negativeBar: { backgroundColor: '#9B3B4E' }, positions: { gap: 7, marginTop: 11 }, row: { flexDirection: 'row', justifyContent: 'space-between' }, symbol: { color: colors.text, fontSize: 10, fontWeight: '600' }, positionPerformance: { fontSize: 10, fontWeight: '700' }, muted: { color: colors.textMuted, fontSize: 9 }, value: { color: colors.text, fontSize: 10 }, record: { color: colors.textMuted, fontSize: 8, marginTop: 9 }, link: { color: colors.textMuted, fontSize: 9, fontWeight: '600', marginTop: 11, paddingTop: 9, borderTopWidth: 1, borderTopColor: colors.border } });
