import { StyleSheet, Text, View } from 'react-native';
import { colors } from '../../theme/colors';
import type { PublicPosition } from '../../types/social';
import { formatPercent, formatPrice } from '../../utils/socialFormatters';

export function PublicPositionCard({ position }: { position: PublicPosition }) {
  const positive = position.performancePercent >= 0; const hasDetails = position.showEntryPrice || position.showCurrentPrice || position.showPositionValue || position.showEntryDate || position.showAllocation;
  return <View style={styles.card}><View style={styles.heading}><View style={styles.asset}><Text style={styles.symbol}>{position.assetSymbol.slice(0, 1)}</Text></View><View><Text style={styles.assetName}>{position.assetSymbol}</Text><Text style={styles.name}>{position.assetName}</Text></View>{position.showPerformance ? <View style={styles.performance}><Text style={styles.label}>SINCE ENTRY</Text><Text style={[styles.performanceValue, { color: positive ? colors.accent : colors.danger }]}>{formatPercent(position.performancePercent, 2)}</Text></View> : null}</View>{hasDetails ? <View style={styles.rows}>{position.showEntryPrice && position.entryPrice ? <Row label="Entry" value={formatPrice(position.entryPrice)}/> : null}{position.showCurrentPrice && position.currentPrice ? <Row label="Current" value={formatPrice(position.currentPrice)}/> : null}{position.showPositionValue && position.positionValue ? <Row label="Public position value" value={formatPrice(position.positionValue)}/> : null}{position.showEntryDate && position.entryDate ? <Row label="Entry date" value={position.entryDate}/> : null}{position.showAllocation && position.allocationPercent !== undefined ? <Row label="Portfolio allocation" value={`${position.allocationPercent}%`}/> : null}</View> : null}<Text style={styles.publicLabel}>Shared by user · Public activity</Text></View>;
}
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ card: { marginTop: 11, borderRadius: 12, borderWidth: 1, borderColor: '#303237', backgroundColor: '#16181A', padding: 12 }, heading: { flexDirection: 'row', alignItems: 'center', gap: 9 }, asset: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#2E343A', alignItems: 'center', justifyContent: 'center' }, symbol: { color: colors.text, fontSize: 13, fontWeight: '800' }, assetName: { color: colors.text, fontSize: 12, fontWeight: '700' }, name: { color: colors.textMuted, fontSize: 9, marginTop: 2 }, performance: { marginLeft: 'auto', alignItems: 'flex-end' }, label: { color: colors.textMuted, fontSize: 7 }, performanceValue: { fontSize: 15, fontWeight: '800', marginTop: 2 }, rows: { borderTopWidth: 1, borderTopColor: colors.border, marginTop: 11, paddingTop: 8, gap: 7 }, row: { flexDirection: 'row', justifyContent: 'space-between' }, rowLabel: { color: colors.textMuted, fontSize: 9 }, rowValue: { color: colors.text, fontSize: 10, fontWeight: '600' }, publicLabel: { color: colors.textFaint, fontSize: 7, marginTop: 10 } });
