import { BarChart3, BellRing, Bot, Check, ChevronDown, Minus, Plus, TrendingUp, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { Market, Outcome } from '../types';
import { Button, IconButton, Modal, Toggle } from './ui';
import { useApp } from '../store/AppStore';

export function MiniChart({values=[44,48,45,54,51,58,61,59,68,66,72,78]}:{values?:number[]}){const points=values.map((v,i)=>`${(i/(values.length-1))*100},${100-v}`).join(' ');const chartColor=(values[values.length-1]??0)>=(values[0]??0)?'#39d98a':'#ff5773';return <svg className="mini-chart" viewBox="0 0 100 60" preserveAspectRatio="none" aria-label="Probability trend"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={chartColor} stopOpacity=".28"/><stop offset="1" stopColor={chartColor} stopOpacity="0"/></linearGradient></defs><polygon points={`0,60 ${points} 100,60`} fill="url(#chart-fill)"/><polyline points={points} fill="none" stroke={chartColor} strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>}

export function ProbabilityChart({market}:{market:Market}){const colors=['#1677ff','#ff7b3b','#43c6d5','#9e91ee'];return <div className="probability-chart"><div className="chart-grid"/><svg viewBox="0 0 800 260" preserveAspectRatio="none" role="img" aria-label="Outcome probability history">{market.outcomes.slice(0,4).map((o,index)=>{const base=o.probability;const values=[base-8,base-5,base-7,base-2,base-3,base+2,base-1,base+3,base+1,base];const points=values.map((v,i)=>`${i*88.8},${250-v*2.25}`).join(' ');return <polyline key={o.label} points={points} fill="none" stroke={o.color||colors[index]} strokeWidth="3" vectorEffect="non-scaling-stroke"/>})}</svg><span className="chart-time start">08/27 22:30</span><span className="chart-time end">08/28 22:22</span></div>}

export function AskAIButton({marketId}:{marketId:string}){const navigate=useNavigate();return <button className="ask-ai" onClick={e=>{e.stopPropagation();navigate(`/app/market/${marketId}/intelligence`);}}><span className="wave-icon"><span/><Bot/></span><span><strong>Ask PredictAI</strong><small>Research this event</small></span></button>}

export function MarketCard({market,onTrade}:{market:Market;onTrade:(market:Market,outcome:Outcome)=>void}){const navigate=useNavigate();return <article className="market-card" tabIndex={0} onClick={()=>navigate(`/app/market/${market.id}`)} onKeyDown={e=>{if(e.key==='Enter')navigate(`/app/market/${market.id}`)}}><div className="market-card-head"><span className={`category-pill ${market.category.toLowerCase()}`}>{market.category}</span><span className="volume">{market.volume} volume</span></div><h3>{market.title}</h3><div className="market-outcomes">{market.outcomes.slice(0,2).map((outcome,index)=><div className="market-outcome" key={outcome.label}><span className={`token ${market.category==='Crypto'?'bitcoin':''}`}>{market.category==='Crypto'?'₿':outcome.label[0]}</span><span className="outcome-name">{outcome.label}</span><small>{outcome.odds}</small><button className={`trade-chip ${outcome.tradeAction==='Sell'?'sell':''}`} onClick={e=>{e.stopPropagation();onTrade(market,outcome);}}>{market.category==='Crypto'?outcome.tradeAction:`${outcome.probability}%`}</button></div>)}</div><AskAIButton marketId={market.id}/><footer><span>{market.subcategory}</span><button onClick={e=>{e.stopPropagation();navigate(`/app/market/${market.id}`);}}>+{market.more} more <ChevronDown/></button></footer></article>}

type Order={market:Market;outcome:Outcome};
export function TradeTicket({order,onClose}:{order:Order|null;onClose:()=>void}){const[step,setStep]=useState<'amount'|'confirm'|'success'>('amount');const[amount,setAmount]=useState('');const numeric=Number(amount)||0;const multiplier=order?Number(order.outcome.odds.replace('x',''))||1:1;const win=numeric*multiplier;const {toast}=useApp();const close=()=>{setStep('amount');setAmount('');onClose();};return <Modal open={!!order} title={step==='success'?undefined:'Place prediction'} onClose={close}>{order&&<>{step==='amount'&&<div className="trade-ticket"><div className="selected-contract"><span>{order.market.category==='Crypto'?'₿':order.outcome.label[0]}</span><div><small>{order.market.title}</small><strong>{order.outcome.label}</strong></div><b>{order.market.category==='Crypto'?order.outcome.tradeAction:`${order.outcome.probability}%`}</b></div><label>Prediction amount<div className="amount-field"><span>USDC</span><input autoFocus inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} placeholder="0.00"/></div></label><div className="quick-amounts">{[10,25,50,100].map(v=><button key={v} onClick={()=>setAmount(String(v))}>{v}</button>)}</div><div className="potential-win"><span><TrendingUp/> Potential win</span><strong>{win.toFixed(2)} USDC</strong><small>Includes your {numeric.toFixed(2)} USDC stake · {order.outcome.odds}</small></div><div className="balance-line"><span>Available balance</span><strong>1,000.00 USDC</strong></div><Button disabled={numeric<=0||numeric>1000} onClick={()=>setStep('confirm')}>Review prediction</Button></div>}{step==='confirm'&&<div className="trade-ticket"><div className="confirm-icon"><BarChart3/></div><h3>Confirm your prediction</h3><div className="summary-list"><span>Event <strong>{order.market.title}</strong></span><span>Outcome <strong>{order.outcome.label}</strong></span><span>Amount <strong>{numeric.toFixed(2)} USDC</strong></span><span>Potential win <strong className="positive">{win.toFixed(2)} USDC</strong></span></div><p className="fine-print">Predictions cannot be changed after confirmation. Resolution follows the event’s published rules.</p><div className="button-row"><Button variant="secondary" onClick={()=>setStep('amount')}>Back</Button><Button onClick={()=>setStep('success')}>Confirm prediction</Button></div></div>}{step==='success'&&<div className="success-panel trade-success"><span className="success-icon"><Check/></span><h2>Prediction placed</h2><p>Your {numeric.toFixed(2)} USDC prediction on <strong>{order.outcome.label}</strong> was successful.</p><div className="potential-win"><span>Potential win</span><strong>{win.toFixed(2)} USDC</strong></div><Button onClick={()=>{toast('Prediction placed successfully','success');close();}}>Done</Button></div>}</>}</Modal>}

export function AlertsModal({market,onClose}:{market:Market|null;onClose:()=>void}){const[movement,setMovement]=useState(true);const[closing,setClosing]=useState(true);const[resolved,setResolved]=useState(true);const[target,setTarget]=useState(false);const[threshold,setThreshold]=useState(5);const[targetValue,setTargetValue]=useState('75');const{toast}=useApp();return <Modal open={!!market} title="Event alerts" onClose={onClose}><p className="modal-subtitle">{market?.title}</p><Setting label="Probability movement" text="Notify when probability changes significantly." value={movement} set={setMovement}/>{movement&&<div className="quick-amounts">{[5,10,15].map(v=><button className={threshold===v?'active':''} key={v} onClick={()=>setThreshold(v)}>{v}%</button>)}</div>}<Setting label="Event closing" text="Receive a reminder before predictions close." value={closing} set={setClosing}/><Setting label="Event resolved" text="Know when the final outcome is confirmed." value={resolved} set={setResolved}/><Setting label="Target probability" text="Notify when an outcome reaches your target." value={target} set={setTarget}/>{target&&<label>Target probability<div className="amount-field"><input value={targetValue} onChange={e=>setTargetValue(e.target.value.replace(/\D/g,'').slice(0,3))}/><span>%</span></div></label>}<Button onClick={()=>{toast('Event alert preferences saved','success');onClose();}}>Save alerts</Button></Modal>}
function Setting({label,text,value,set}:{label:string;text:string;value:boolean;set:(v:boolean)=>void}){return <div className="setting-row"><div><strong>{label}</strong><p>{text}</p></div><Toggle label={label} checked={value} onChange={set}/></div>}

export function OutcomeSelector({market,onTrade}:{market:Market;onTrade:(o:Outcome)=>void}){const[expanded,setExpanded]=useState(false);const shown=expanded?market.outcomes:market.outcomes.slice(0,3);return <div className="outcome-selector">{shown.map((o,i)=><button key={o.label} onClick={()=>onTrade(o)}><span className="legend-dot" style={{background:o.color||['#1677ff','#ff7b3b','#43c6d5','#9e91ee'][i]}}/><span>{o.label}</span><small>{o.odds}</small><b className={o.tradeAction==='Sell'?'negative':''}>{market.category==='Crypto'?o.tradeAction:`${o.probability}%`}</b></button>)}{!expanded&&market.more>0&&<button className="more-outcomes" onClick={()=>setExpanded(true)}><Plus/> {market.more} more outcomes</button>}{expanded&&<button className="more-outcomes" onClick={()=>setExpanded(false)}><Minus/> Show fewer</button>}</div>}
