import { useEffect, useMemo, useState } from 'react'; import { Ionicons } from '@expo/vector-icons'; import * as LocalAuthentication from 'expo-local-authentication'; import { Pressable, StyleSheet, Text, View } from 'react-native'; import { colors } from '../theme/colors';
function maskEmail(email: string) { const [name = '', domain = ''] = email.split('@'); return `${name.slice(0, 2)}${name.length > 2 ? '***' : ''}@${domain}`; }
export function BiometricScreen({ email, onUsePassword }: { email: string; onUsePassword: () => void }) {
  const [message, setMessage] = useState('Please verify biometrics to unlock'); const maskedEmail = useMemo(() => maskEmail(email), [email]);
  const authenticate = async () => { const compatible = await LocalAuthentication.hasHardwareAsync(); const enrolled = compatible && await LocalAuthentication.isEnrolledAsync(); if (!enrolled) { setMessage('Biometrics are not configured on this device'); return; } const result = await LocalAuthentication.authenticateAsync({ promptMessage: 'Unlock PredictAI', cancelLabel: 'Use password', fallbackLabel: 'Use password' }); setMessage(result.success ? 'PredictAI unlocked' : 'Biometric verification was not completed'); };
  useEffect(() => { void authenticate(); }, []);
  return <View style={styles.root}><View style={styles.intro}><Text style={styles.title}>Welcome</Text><Text style={styles.email}>{maskedEmail}</Text></View><Pressable accessibilityLabel="Authenticate with biometrics" onPress={authenticate} style={styles.biometric}><Ionicons color={colors.accent} name="finger-print" size={112} /><Text style={styles.message}>{message}</Text></Pressable><Pressable onPress={onUsePassword} style={styles.passwordButton}><Text style={styles.passwordText}>Log in via password</Text></Pressable></View>;
}
const styles = StyleSheet.create({ root: { flex: 1, paddingHorizontal: 17 }, intro: { alignItems: 'center', marginTop: 145 }, title: { color: colors.text, fontSize: 23, fontWeight: '700' }, email: { color: colors.textMuted, fontSize: 14, marginTop: 7 }, biometric: { alignItems: 'center', marginTop: 120, transform: [{ scale: 0.72 }] }, message: { color: colors.textMuted, fontSize: 16, lineHeight: 22, fontWeight: '600', textAlign: 'center', marginTop: 22 }, passwordButton: { alignSelf: 'center', marginTop: 'auto', marginBottom: 115, padding: 11 }, passwordText: { color: colors.text, fontSize: 16 } });
